import type { Playbook } from '../types'
import { bi } from '../i18n'

export const backupPlaybook: Playbook = {
  id: 'backup-local',
  category: 'backup',
  title: { en: 'Save a copy of your gym', ar: 'احفظ نسخة من النادي' },
  purpose: {
    en: 'Make a copy of this gym on this PC: the database and member photos. Cloud gyms do not have this page.',
    ar: 'اعمل نسخة من النادي على الجهاز: قاعدة البيانات وصور الأعضاء. النوادي السحابية مفيهاش الصفحة دي.',
  },
  whenToUse: {
    en: 'First day, every week, and before any restore.',
    ar: 'أول يوم، كل أسبوع، وقبل أي استعادة.',
  },
  preconditions: [
    bi('You are the gym owner on this PC.', 'أنت مالك النادي على الجهاز ده.'),
  ],
  requiredAccess: {
    en: 'Gym owner for Backup now. Windows Administrator only if you need to register the nightly task.',
    ar: 'مالك النادي لزر النسخ. مسؤول ويندوز بس لو هتسجّل المهمة الليلية.',
  },
  risk: 'admin',
  audience: 'both',
  customerSummary: {
    en: 'We keep a copy of your gym on this computer. If the computer is stolen or the disk dies, that copy is gone unless you also copied the Backups folder to a USB or another disk.',
    ar: 'بنحتفظ بنسخة من ناديكم على الجهاز. لو الجهاز اتسرق أو القرص عطل، النسخة تضيع إلا لو نسختوا مجلد النسخ على USB أو قرص تاني.',
  },
  steps: [
    {
      id: 'open',
      action: bi('Open HyMotion. Go to Backup.', 'افتح HyMotion. روح النسخ.'),
      who: 'owner',
      expected: bi('You see a list of copies, not the home screen.', 'شايف قائمة نسخ، مش الشاشة الرئيسية.'),
      verification: bi('The page title is about backup. If you bounced home, tap I need help.', 'عنوان الصفحة عن النسخ. لو رجعت للرئيسية، اضغط محتاج مساعدة.'),
      risk: 'safe',
      audience: 'both',
      tech: bi(
        'Route is OwnerOnly. SaaS Desk returns 404 for this page. Do not treat a missing nav item as a backup failure.',
        'المسار للمالك بس. المكتب السحابي بيرجع 404. اختفاء العنصر من القائمة مش معناه فشل نسخ.',
      ),
    },
    {
      id: 'manual',
      action: bi('Click Save a copy now. Wait about one minute. Click Refresh.', 'اضغط احفظ نسخة دلوقتي. استنى حوالي دقيقة. اضغط تحديث.'),
      who: 'owner',
      expected: bi('A new row appears. It should say the copy is good. Partial means members copied but some photos did not.', 'صف جديد يظهر. المفروض يقول النسخة كويسة. جزئي يعني الأعضاء اتنسخوا وبعض الصور لأ.'),
      verification: bi('The new row is not Failed. If it failed, tap I need help.', 'الصف الجديد مش فشل. لو فشل، اضغط محتاج مساعدة.'),
      failurePath: bi('If the message says the backup script is missing, support must copy the backup scripts next to the HyMotion program.', 'لو الرسالة إن سكربت النسخ مش موجود، الدعم لازم ينسخ سكربتات النسخ جنب برنامج HyMotion.'),
      risk: 'safe',
      audience: 'both',
      tech: bi(
        'Desk POST /backup/run starts Backup-HyMotion.ps1 from install-scripts\\backup next to GMS.Api.exe. Token: gfp_access_token / GfpApi.tokens.getAccess. Typical output folder: C:\\ProgramData\\HyMotion\\Backups\\HyMotionBackup_yyyy-MM-dd_HHmmss\\ (database.bak, uploads.zip, manifest.json).',
        'المكتب POST /backup/run بيشغّل Backup-HyMotion.ps1 من install-scripts\\backup جنب GMS.Api.exe. التوكن: gfp_access_token. المجلد: C:\\ProgramData\\HyMotion\\Backups\\HyMotionBackup_yyyy-MM-dd_HHmmss\\ وفيه database.bak و uploads.zip و manifest.json.',
      ),
    },
    {
      id: 'location',
      action: bi('Read Saved on this PC. That is where the copy lives.', 'اقرأ المكان على الجهاز. ده مكان النسخة.'),
      who: 'support',
      expected: bi('The folder exists. Each run is its own folder with three files: database, photos zip, and a small manifest.', 'المجلد موجود. كل تشغيل ليه مجلد فيه ثلاثة ملفات: القاعدة، ضغط الصور، وملف بيان.'),
      verification: bi('The folder name matches the backup id in the manifest. Do not add extra quotes around the id.', 'اسم المجلد يطابق معرف النسخة في ملف البيان. متزودش علامات اقتباس زيادة.'),
      risk: 'safe',
      audience: 'support',
      tech: bi(
        'Default path C:\\ProgramData\\HyMotion\\Backups. Id format HyMotionBackup_yyyy-MM-dd_HHmmss. Safety copies before restore are PreRestore_* in the same parent. Logs: C:\\ProgramData\\HyMotion\\logs\\backup-YYYY-MM-DD.log.',
        'المسار الافتراضي C:\\ProgramData\\HyMotion\\Backups. الشكل HyMotionBackup_yyyy-MM-dd_HHmmss. النسخ الاحترازية قبل الاستعادة PreRestore_* في نفس المجلد الأب. السجلات: C:\\ProgramData\\HyMotion\\logs\\backup-YYYY-MM-DD.log.',
      ),
    },
    {
      id: 'healthy',
      action: bi('Use Healthy copies for restore. A Failed copy is not allowed. Partial is last resort and may miss photos.', 'استخدم النسخ السليمة للاستعادة. الفاشلة ممنوع. الجزئية آخر حل وممكن تنقص صور.'),
      who: 'support',
      expected: bi('Before go-live there is at least one Healthy copy named HyMotionBackup_…', 'قبل التشغيل فيه على الأقل نسخة سليمة اسمها HyMotionBackup_…'),
      verification: bi('History Status = Healthy and the database verified mark is on.', 'حالة السجل سليم وعلامة تأكد القاعدة متعلمة.'),
      risk: 'safe',
      audience: 'support',
      tech: bi(
        'Restore-HyMotion.ps1 -Latest picks the newest Healthy HyMotionBackup_* only. Partial is skipped by -Latest; it may still restore with -BackupId if hashes match. Test-BackupIntegrity rejects status Failed even if files look present.',
        '-Latest بيختار أحدث HyMotionBackup_* سليم بس. الجزئي بيتعدّى؛ ممكن -BackupId لو الهاش مطابق. Test-BackupIntegrity بيرفض Failed حتى لو الملفات ظاهرة.',
      ),
    },
    {
      id: 'verify-limit',
      action: bi('A Healthy mark is not always a full SQL “verify only” check. The Windows service account has limited SQL rights.', 'علامة سليم مش دايمًا فحص SQL كامل. حساب خدمة ويندوز صلاحياته SQL محدودة.'),
      who: 'support',
      expected: bi('The copy on disk can still be used if the script fell back to listing files or checking the file checksum.', 'النسخة على القرص ممكن تتعمل لو السكربت اكتفى بقائمة الملفات أو فحص المجموع.'),
      verification: bi('Open today’s backup log and see which verify method it used.', 'افتح سجل النسخ النهارده وشوف طريقة التأكد.'),
      risk: 'support_only',
      audience: 'support',
      tech: bi(
        'Service: HyMotion as NT AUTHORITY\\NETWORK SERVICE, db_owner on HyMotionLocal only — not CREATE DATABASE / sysadmin. Test-SqlBackupMedia: RESTORE VERIFYONLY → FILELISTONLY → fallback BackupFile (file present + CHECKSUM). Log may say verified (VerifyOnly), (FileListOnly), or (BackupFile). VERIFYONLY often fails with CREATE DATABASE permission denied / VERIFY DATABASE is terminating abnormally.',
        'الخدمة HyMotion بحساب NETWORK SERVICE، db_owner على HyMotionLocal بس — من غير CREATE DATABASE. الترتيب: VERIFYONLY ثم FILELISTONLY ثم BackupFile (وجود الملف + CHECKSUM). السجل ممكن يقول VerifyOnly أو FileListOnly أو BackupFile. VERIFYONLY غالبًا يفشل بـ CREATE DATABASE denied.',
      ),
    },
    {
      id: 'nightly',
      action: bi('Check Next scheduled run. If it says not scheduled, register the nightly task (installer usually does this).', 'شوف التشغيل الجاي. لو مش متجدول، سجّل المهمة الليلية (المثبّت عادةً بيعملها).'),
      who: 'support',
      expected: bi('A time is shown. Backup now still works even if the task is missing; overnight copies will not.', 'فيه وقت ظاهر. زر النسخ يشتغل حتى لو المهمة مش موجودة؛ النسخ بالليل لأ.'),
      verification: bi('Task Scheduler shows HyMotion Nightly Backup at 02:00, or the Desk KPI has a next run.', 'جدولة المهام فيها HyMotion Nightly Backup الساعة 2:00، أو المؤشر في الصفحة فيه وقت.'),
      failurePath: bi('Missing task is not a reason to restore. Fix the task, then take Backup now if you need a copy today.', 'المهمة الناقصة مش سبب للاستعادة. صلّح المهمة، وبعدين نسخ دلوقتي لو محتاج نسخة النهارده.'),
      risk: 'admin',
      audience: 'support',
      commands: [
        {
          id: 'reg-task',
          label: bi('Register nightly task (from the folder that has GMS.Api.exe)', 'تسجيل المهمة الليلية (من مجلد GMS.Api.exe)'),
          text: '.\\install-scripts\\backup\\Register-BackupTask.ps1',
          supportOnly: true,
        },
      ],
      tech: bi(
        'Task name: HyMotion Nightly Backup. Runs as NETWORK SERVICE. Register from the running service directory (Get-CimInstance Win32_Service Name=HyMotion PathName) — do not assume Program Files. Dev folder publishes must copy scripts/local-install/backup/*.ps1 into install-scripts\\backup.',
        'اسم المهمة: HyMotion Nightly Backup. بتشتغل كـ NETWORK SERVICE. سجّل من مجلد الخدمة الشغالة (PathName) — متفترضش Program Files. نشر التطوير لازم ينسخ سكربتات backup إلى install-scripts\\backup.',
      ),
    },
    {
      id: 'offpc',
      action: bi('Plug in a USB. Click Save to USB. Wait until it finishes.', 'وصل فلاشة. اضغط احفظ على USB. استنى لحد ما يخلّص.'),
      who: 'owner',
      expected: bi('The stick has a copy of your gym. A copy only on this PC dies if the PC dies.', 'الفلاشة فيها نسخة من النادي. النسخة على الجهاز بس تموت لو الجهاز مات.'),
      verification: bi('You can unplug the USB. Keep it somewhere safe, not in the till.', 'تقدر تشيل الفلاشة. خليها في مكان آمن، مش في الدرج.'),
      risk: 'safe',
      audience: 'both',
      tech: bi(
        'Owner path: hymotion-backup:usb → HyMotionBackup.exe copies the chosen folder to <USB>:\\HyMotionBackups\\. Optional offPcDestination in backup-config.json is still support-only. Local Edition has no SaaS/cloud backup pull.',
        'مسار المالك: hymotion-backup:usb → HyMotionBackup.exe بينسخ المجلد إلى <USB>:\\HyMotionBackups\\. offPcDestination للدعم. مفيش سحب سحابة للمحلي.',
      ),
    },
  ],
  failures: [
    {
      id: 'script-missing',
      title: bi('Backup did not start — scripts missing', 'النسخ ما بدأش — السكربتات مش موجودة'),
      whatHappened: bi('The program looked for backup files next to itself and did not find them.', 'البرنامج دور على ملفات النسخ جنبه ومالقهاش.'),
      doNot: bi('Do not invent another backup tool. Do not restore from a random .bak file.', 'متستخدمش أداة نسخ تانية. متستعيدش من ملف .bak عشوائي.'),
      immediate: bi('Copy the backup scripts from the installer (or a good publish folder) next to GMS.Api.exe, then Backup now again.', 'انسخ سكربتات النسخ من المثبّت جنب GMS.Api.exe، وبعدين نسخ دلوقتي تاني.'),
      recovery: bi('A folder copy of the API without that step will always fail this way.', 'نسخ مجلد الـ API من غير الخطوة دي هيفشل كده دايمًا.'),
      escalation: bi('Escalate if nobody knows where GMS.Api.exe is running from, or the installer never shipped backup scripts.', 'صعّد لو محدش عارف مجلد التشغيل، أو المثبّت من غير سكربتات.'),
      logs: bi('Desk toast or banner. No new folder under Backups.', 'رسالة في المكتب. مفيش مجلد جديد تحت Backups.'),
      customerMessage: bi('Backup did not start because backup files are missing on this PC. Support will copy them.', 'النسخ ما بدأش لأن ملفات النسخ مش على الجهاز. الدعم هينسخها.'),
      closure: bi('Backup now creates a Healthy or Partial row.', 'نسخ دلوقتي يعمل صف سليم أو جزئي.'),
      audience: 'support',
      tech: bi(
        'Required file: <service dir>\\install-scripts\\backup\\Backup-HyMotion.ps1. Resolve service dir with Win32_Service PathName for Name=HyMotion, not a guessed Program Files path. Inno DestDir {app}\\install-scripts\\backup. publish-local.ps1 must copy scripts/local-install/backup.',
        'الملف المطلوب: مجلد الخدمة\\install-scripts\\backup\\Backup-HyMotion.ps1. المسار من PathName للخدمة HyMotion. المثبّت يحطها تحت {app}\\install-scripts\\backup.',
      ),
    },
    {
      id: 'create-db',
      title: bi('SQL said CREATE DATABASE denied while checking the copy', 'SQL رفض CREATE DATABASE أثناء فحص النسخة'),
      whatHappened: bi('The database file was written. The extra SQL check needs a right the service account does not have.', 'ملف القاعدة اتكتب. فحص SQL الزيادة محتاج صلاحية حساب الخدمة مالوش.'),
      doNot: bi('Do not give the service account sysadmin. Do not delete the .bak.', 'متديش حساب الخدمة sysadmin. متمسحش ملف القاعدة.'),
      immediate: bi('Refresh the page. Current scripts may still mark Healthy after a weaker file check.', 'حدّث الصفحة. السكربت الحالي ممكن يعلّم سليم بعد فحص ملف أضعف.'),
      recovery: bi('Take another Backup now after scripts are current. Old Failed rows stay unrestorable in the official script.', 'خد نسخة تانية بعد تحديث السكربت. الصفوف الفاشلة القديمة تفضل مش قابلة للاستعادة بالسكربت الرسمي.'),
      escalation: bi('Escalate if every new run is still Failed after the fallback script is on disk.', 'صعّد لو كل تشغيل جديد لسه فشل بعد وجود سكربت التراجع.'),
      logs: bi('C:\\ProgramData\\HyMotion\\logs\\backup-YYYY-MM-DD.log', 'C:\\ProgramData\\HyMotion\\logs\\backup-YYYY-MM-DD.log'),
      customerMessage: bi('A copy was written. We will confirm a Healthy row before we rely on it.', 'اتكتبت نسخة. هنتأكد إن الصف سليم قبل ما نعتمد عليها.'),
      closure: bi('Newest HyMotionBackup_* is Healthy.', 'أحدث HyMotionBackup_* سليم.'),
      audience: 'support',
      tech: bi(
        'BACKUP DATABASE as NETWORK SERVICE can succeed while RESTORE VERIFYONLY fails (CREATE DATABASE permission denied; VERIFY DATABASE is terminating abnormally). Fallback is FILELISTONLY then BackupFile checksum. Do not grant CREATE DATABASE/sysadmin to NETWORK SERVICE. Failed status in manifest blocks Restore-HyMotion even if hashes later match.',
        'BACKUP DATABASE ممكن ينجح و VERIFYONLY يفشل. التراجع FILELISTONLY ثم checksum. متديش CREATE DATABASE لـ NETWORK SERVICE. حالة Failed في manifest بتمنع Restore-HyMotion.',
      ),
    },
    {
      id: 'partial',
      title: bi('Partial backup (database ok, some files skipped)', 'نسخة جزئية (القاعدة تمام، ملفات اتعدّت)'),
      whatHappened: bi('The database copied. Some photo or upload files were locked or unreadable.', 'القاعدة اتنسخت. بعض الصور أو الملفات كانت مقفولة أو متعذر قراءتها.'),
      doNot: bi('Do not treat this as the only go-live copy if member photos matter.', 'متعتبرهاش النسخة الوحيدة للتشغيل لو صور الأعضاء مهمة.'),
      immediate: bi('Close programs that lock files, then Backup now again.', 'اقفل البرامج اللي ماسكة الملفات، وبعدين نسخ دلوقتي تاني.'),
      recovery: bi('You may restore this folder by id if hashes match. Skipped files will still be missing.', 'ممكن تستعيد المجلد بالمعرف لو الهاش مطابق. الملفات المتعدّية هتفضل ناقصة.'),
      escalation: bi('Escalate if the skipped files are member photos the gym needs.', 'صعّد لو الملفات المتعدّية صور أعضاء النادي محتاجها.'),
      logs: bi('manifest.json → uploads.skippedFiles', 'manifest.json → uploads.skippedFiles'),
      customerMessage: bi('The database copied. Some files did not. We will retry.', 'القاعدة اتنسخت. بعض الملفات لأ. هنحاول تاني.'),
      closure: bi('A later Healthy complete copy exists, or the owner accepts Partial.', 'فيه نسخة سليمة كاملة لاحقة، أو المالك يقبل الجزئي.'),
      audience: 'support',
      tech: bi(
        'Uploads source is C:\\ProgramData\\HyMotion\\uploads. -Latest will not select Partial. -BackupId can restore if Test-BackupIntegrity hashes match. skippedFiles in manifest lists what will be missing after restore.',
        'مصدر الملفات C:\\ProgramData\\HyMotion\\uploads. -Latest مش بيختار Partial. -BackupId ممكن لو الهاش مطابق. skippedFiles هتبقى ناقصة بعد الاستعادة.',
      ),
    },
  ],
  recovery: {
    en: 'Fix scripts, disk, or the nightly task. Then click Backup now. Do not restore to “fix” a backup that failed.',
    ar: 'صلّح السكربت أو القرص أو المهمة الليلية. وبعدين نسخ دلوقتي. متستعيدش عشان «تصلّح» نسخ فشل.',
  },
  escalation: {
    en: 'Escalate when Backup now keeps failing after scripts sit next to GMS.Api.exe, or when SQL cannot write database.bak at all.',
    ar: 'صعّد لو نسخ دلوقتي يفضل يفشل بعد وجود السكربتات جنب GMS.Api.exe، أو SQL مش قادر يكتب ملف القاعدة أصلًا.',
  },
  customerCommunication: {
    en: 'Copies live under ProgramData on this PC. Use Save to USB so the stick has HyMotionBackups. A Failed row cannot be used to restore.',
    ar: 'النسخ تحت ProgramData على الجهاز. استخدم احفظ على USB عشان الفلاشة يبقى فيها HyMotionBackups. الصف الفاشل مش بيتستعاد منه.',
  },
  securityWarnings: [
    bi('Backup folders contain the gym database. Treat USB copies as confidential.', 'مجلدات النسخ فيها قاعدة النادي. اعتبروا نسخ USB سرية.'),
    bi('Do not email database.bak.', 'متبعتوش database.bak بالإيميل.'),
  ],
  finalVerification: [
    bi('At least one Healthy HyMotionBackup_* (or an accepted Partial if photos do not matter).', 'على الأقل HyMotionBackup_* سليم (أو جزئي مقبول لو الصور مش مهمة).'),
    bi('Owner knows Open Restore launches HyMotion Backup — type RESTORE there, not in PowerShell.', 'المالك يعرف إن افتح الاستعادة بيفتح HyMotion Backup — اكتب RESTORE هناك مش في PowerShell.'),
  ],
  closure: [
    bi('Healthy backup exists', 'نسخة سليمة موجودة'),
    bi('Owner shown Backup & Recovery page', 'المالك شاف صفحة النسخ'),
    bi('Nightly task: present or documented gap', 'المهمة الليلية: موجودة أو الفجوة موثّقة'),
    bi('Off-PC recommendation given', 'اتقالت توصية النسخة برا الجهاز'),
  ],
}
