import type { Playbook } from '../types'
import { bi } from '../i18n'

export const customerOnboardPlaybook: Playbook = {
  id: 'customer-onboard',
  category: 'setup',
  title: { en: 'Control Plane — onboard a customer', ar: 'لوحة التحكم — تسجيل عميل' },
  purpose: {
    en: 'Create the commercial record first: Customer → Contract → Payment, then a Local license only if Ops/Admin is present. Do not treat a license as the customer.',
    ar: 'سجّل التجاري الأول: عميل ← عقد ← دفعة، وبعدين ترخيص محلي لو عمليات/إدارة موجودين. متعتبرش الترخيص هو العميل.',
  },
  whenToUse: {
    en: 'Every new Local gym sale, before you travel with the field kit. Also when a SaaS gym is sold as a named customer (then provision the tenant separately).',
    ar: 'كل بيع نادي محلي جديد، قبل سفر حقيبة الدعم. وكمان لو صالة سحابية اتباعت كعميل بالاسم (بعدين وفّر الصالة لوحدها).',
  },
  preconditions: [
    bi('You are signed in to the HyMotion Platform Console (not the gym Desk).', 'داخل على لوحة تحكم المنصة (مش مكتب النادي).'),
    bi('Sales can create customers, contracts, and payments. Only Ops/Admin can issue, suspend, revoke, reactivate, or transfer a Local license.', 'المبيعات تقدر تعمل عميل وعقد ودفعة. العمليات/الإدارة بس تصدر أو توقف أو تسحب أو تعيد أو تنقل ترخيص محلي.'),
  ],
  requiredAccess: {
    en: 'Sales or above to write customers/contracts/payments. Ops/Admin to issue the license. Do not store a gym owner password anywhere in this console.',
    ar: 'مبيعات فأعلى لكتابة العميل/العقد/الدفعة. عمليات/إدارة لإصدار الترخيص. متتخزنش كلمة سر مالك النادي في اللوحة دي.',
  },
  risk: 'admin',
  audience: 'support',
  customerSummary: {
    en: 'We are registering your gym as a HyMotion customer and the items you purchased. You will get a license key only when operations issues it. We will never ask you to paste a password into this console.',
    ar: 'بنسجّل ناديكم كعميل HyMotion والأصناف اللي اشتريتوها. مفتاح الترخيص ييجي لما العمليات تصدره. مش هنطلب لصق كلمة سر في اللوحة دي.',
  },
  lifecycle: [
    bi('Customer', 'عميل'),
    bi('Contract', 'عقد'),
    bi('Payment', 'دفعة'),
    bi('License (Ops)', 'ترخيص (عمليات)'),
    bi('Owner metadata', 'بيانات المالك'),
    bi('Handover / field visit', 'تسليم / زيارة'),
  ],
  steps: [
    {
      id: 'open',
      action: bi('Open Customers → Onboard customer. If POST fails with Request failed (404), the API was not restarted after this feature shipped — restart GMS.Api with the https profile, then retry. Do not retype the form as the fix.', 'افتح العملاء ← تسجيل عميل. لو الطلب فشل 404، الـ API ما اتعدّاش بعد الميزة — أعد تشغيل GMS.Api بملف https، بعدين حاول. متظبطش الفورم كحل.'),
      who: 'hyMotion',
      expected: bi('Wizard step 1 (Customer) loads. Business name and owner name are required.', 'خطوة العميل بتظهر. اسم النشاط واسم المالك مطلوبين.'),
      verification: bi('GET /platform-api/customers is 401 without a token (route exists) or 200 with your session — never 404.', 'GET /platform-api/customers يبقى 401 من غير توكن (المسار موجود) أو 200 وأنت داخل — مش 404.'),
      risk: 'safe',
      audience: 'support',
      tech: bi('Vite proxies /platform-api to https://localhost:5001. Controllers: PlatformCustomersController. Stale GMS.Api.exe is the usual 404. Restart --launch-profile https after adding routes.', 'البروكسي على 5001. المتحكم PlatformCustomersController. 404 المعتاد من عملية GMS.Api قديمة.'),
    },
    {
      id: 'customer',
      action: bi('Enter the gym/business name, owner name, phone, WhatsApp, email, address, lead source. Click Next. This creates PlatformCustomer — not a license.', 'اكتب اسم النشاط/النادي، اسم المالك، التليفون، واتساب، الإيميل، العنوان، مصدر العميل. اضغط التالي. ده بيعمل عميل منصة — مش ترخيص.'),
      who: 'hyMotion',
      expected: bi('Customer exists on Customers list. Profile tabs: overview, contracts, purchases, payments, licenses, installations, support, activity.', 'العميل ظاهر في القائمة. التبويبات: نظرة، عقود، مشتريات، دفعات، تراخيص، تثبيتات، دعم، نشاط.'),
      verification: bi('Open the customer. Business and owner names match what sales agreed. No password field exists.', 'افتح العميل. الاسمين يطابقوا الاتفاق. مفيش حقل كلمة سر.'),
      risk: 'safe',
      audience: 'support',
      tech: bi('POST /platform-api/customers. Policy PlatformSalesOrAbove for write; PlatformCustomerAccess (Sales+Support+Ops+Admin) for read. Never persist owner passwords.', 'POST /platform-api/customers. الكتابة Sales+. القراءة CustomerAccess. متتخزنش كلمات سر.'),
    },
    {
      id: 'catalog',
      action: bi('On the contract step, pick catalog SKUs (software lifetime, install service, PVC cards, printer, …). Quantities and discounts are snapshots — renaming a catalog product later does not rewrite this contract.', 'في خطوة العقد، اختار أصناف الكتالوج (برنامج مدى الحياة، تركيب، كروت PVC، طابعة، …). الكمية والخصم لقطة — تغيير اسم الصنف بعدين مش هيعدّل العقد ده.'),
      who: 'hyMotion',
      expected: bi('Line items show SKU name, type, unit price. Header discount is optional. Total is the contract total, not an invoice.', 'البنود فيها الاسم والنوع والسعر. خصم رأس اختياري. الإجمالي للعقد مش فاتورة.'),
      verification: bi('Products & services page lists the SKUs. Contract ≠ SaaS PlatformInvoice. License ≠ customer.', 'صفحة المنتجات والخدمات فيها الـ SKU. العقد ≠ فاتورة سحابة. الترخيص ≠ العميل.'),
      risk: 'safe',
      audience: 'support',
      tech: bi('GET /platform-api/catalog-products. Seed SKUs include HY-SW-LOCAL-LT, HY-SVC-INSTALL, HY-HW-PVC, HY-HW-PRINTER. POST /platform-api/contracts snapshots name/type/price.', 'كتالوج المنصة. العقود بتاخد لقطة السعر والاسم.'),
    },
    {
      id: 'contract',
      action: bi('Create the contract, then set status draft → pending → active as the wizard does. Do not skip items. A cancelled contract must not be used to issue a license.', 'أنشئ العقد، بعدين الحالة مسودة ← قيد الانتظار ← نشط زي المعالج. متتخطاش البنود. عقد ملغي متصدرش عليه ترخيص.'),
      who: 'hyMotion',
      expected: bi('Contract number like HY-CTR-yyyy-0000. Payment status unpaid/partial/paid from recorded cash, bank_transfer, or other — not a card gateway.', 'رقم عقد زي HY-CTR-yyyy-0000. حالة الدفع من الدفعات المسجّلة كاش/تحويل/أخرى — مش بوابة كروت.'),
      verification: bi('Contracts list shows the customer. Purchases tab lists the snapshots.', 'قائمة العقود فيها العميل. تبويب المشتريات فيه اللقطات.'),
      risk: 'admin',
      audience: 'support',
      tech: bi('POST /platform-api/contracts then POST .../status. Illegal transitions throw. Payments POST /platform-api/customer-payments — recorded, not Paymob-verified.', 'العقد ثم تغيير الحالة. الدفعات مسجّلة مش متحققة من بوابة.'),
    },
    {
      id: 'payment',
      action: bi('Record the amount actually received (cash / bank transfer / other) and a reference if you have one. Partial payment is allowed. Do not pretend a SaaS invoice was paid.', 'سجّل المبلغ اللي دخل فعلًا (كاش / تحويل / أخرى) ومرجع لو موجود. الدفع الجزئي مسموح. متقولش إن فاتورة سحابة اتدفعت.'),
      who: 'hyMotion',
      expected: bi('Payments tab shows the row. Outstanding = contract total minus paid (cancelled contracts excluded).', 'تبويب الدفعات فيه الصف. المتبقي = إجمالي العقود ناقص المدفوع (من غير الملغي).'),
      verification: bi('Owner-facing story matches the receipt they were given. No card PAN in notes.', 'الكلام مع المالك يطابق الإيصال. متكتبش أرقام كروت في الملاحظات.'),
      risk: 'admin',
      audience: 'support',
    },
    {
      id: 'license',
      action: bi('License step: Ops/Admin only. Issue Local Lifetime against this customer and contract. Sales must stop here and hand to Ops — the wizard hides issue if you are not Ops.', 'خطوة الترخيص: عمليات/إدارة بس. أصدر محلي مدى الحياة على العميل والعقد. المبيعات تقف هنا وتسلّم للعمليات — المعالج بيخفي الإصدار لو مش عمليات.'),
      who: 'hyMotion',
      expected: bi('License key shown once as the product already does. CustomerId/ContractId are set. CustomerName snapshot stays for signing/activation — do not change crypto.', 'مفتاح الترخيص يظهر مرة زي المنتج. CustomerId و ContractId متعينين. اسم العميل لقطة للتوقيع/التفعيل — متغيّرش التشفير.'),
      verification: bi('Licenses list shows the gym. Customer profile Licenses tab matches. Sales cannot Issue/Suspend/Revoke/Transfer.', 'قائمة التراخيص فيها النادي. تبويب التراخيص على العميل يطابق. المبيعات تقدرش تصدر/توقف/تسحب/تنقل.'),
      failurePath: bi('If you are Sales, skip issue, finish owner metadata, and open a Support ticket asking Ops to issue.', 'لو أنت مبيعات، تخطّى الإصدار، كمّل بيانات المالك، وافتح تذكرة للدعم تطلب من العمليات الإصدار.'),
      risk: 'admin',
      audience: 'support',
      tech: bi('POST /platform-api/local-licenses is PlatformOpsOrAbove. Audit platform.license.issued. Device limit stays on the license. Do not duplicate LocalLicense as a second customer table.', 'الإصدار Ops+. حد الأجهزة على الترخيص. متكررش جدول عملاء من التراخيص.'),
    },
    {
      id: 'owner-meta',
      action: bi('Owner step: username/email metadata only. Never type or generate a password. Local gym owner passwords live on the gym PC after first-run setup.', 'خطوة المالك: اسم مستخدم/إيميل كبيانات بس. متكتبش ولا تولّد كلمة سر. كلمات سر مالك المحلي على جهاز النادي بعد أول تجهيز.'),
      who: 'hyMotion',
      expected: bi('Owner account status is metadata. Password-reset later is an audited request — it never returns a password.', 'حالة حساب المالك بيانات. طلب تصفير لاحقًا متسجل — عمره ما يرجّع كلمة سر.'),
      verification: bi('JSON/API has no password field. Owner can sign in only after on-box setup (Local) or SaaS provision.', 'الـ API من غير حقل كلمة سر. الدخول بعد التجهيز على الجهاز أو توفير السحابة.'),
      risk: 'safe',
      audience: 'support',
      tech: bi('PUT /platform-api/customers/{id} for owner email/username. Local owner-password-reset is OpsOrAbove, reason ≥ 10 chars, never generates a password. Cloud Owner: POST /platform-api/tenants/{tenantId}/users/{staffId}/reset-password (Ops+). Gym-side ResetStaffPasswordAsync still refuses Owner.', 'تحديث العميل للإيميل. تصفير المحلي Ops+ ومش بيولّد كلمة سر. مالك السحابة reset-password من المنصة. تصفير الموظفين على الجهاز بيرفض Owner.'),
    },
    {
      id: 'next',
      action: bi('Handover: for Local, open the Field kit playbook and travel. For SaaS, provision the tenant (Ops) and keep this customer linked if TenantId is set. Finish Go-live on site.', 'التسليم: للمحلي افتح دليل الحقيبة وسافر. للسحابة وفّر الصالة (عمليات) واربط TenantId لو موجود. كمّل قبول التشغيل في الموقع.'),
      who: 'support',
      expected: bi('Case has customer id, contract number, payment status, and license key held by Ops — not pasted into a public chat.', 'الحالة فيها رقم العميل والعقد وحالة الدفع ومفتاح الترخيص مع العمليات — مش متلصق في شات عام.'),
      verification: bi('Customer profile Support tab is empty or has only real tickets. Backup/restore stay on the gym PC playbooks.', 'تبويب الدعم فاضي أو فيه تذاكر حقيقية. النسخ/الاستعادة تفضل على أدلة جهاز النادي.'),
      risk: 'safe',
      audience: 'support',
    },
  ],
  failures: [
    {
      id: '404-stale-api',
      title: bi('Onboard Next shows Request failed (404)', 'التالي بيظهر Request failed (404)'),
      whatHappened: bi('The running GMS.Api process does not have POST /platform-api/customers.', 'عملية GMS.Api الشغالة مفيهاش مسار العملاء.'),
      doNot: bi('Do not change the gym name or owner name as the fix. Do not invent a second customer form.', 'متغيّرش اسم النادي كحل. ومتعملش فورم عميل تاني.'),
      immediate: bi('Stop the old GMS.Api on ports 5000/5001, rebuild, start --launch-profile https. Probe GET /platform-api/customers → 401 not 404.', 'وقف GMS.Api القديم على 5000/5001، ابنِ، شغّل https. افحص المسار 401 مش 404.'),
      recovery: bi('Click Next again on the same form after the API is new.', 'اضغط التالي تاني على نفس الفورم بعد ما الـ API يتجدد.'),
      escalation: bi('Escalate if 401/403 after restart (wrong role) or 500 (migration).', 'صعّد لو 401/403 بعد إعادة التشغيل (دور غلط) أو 500 (migration).'),
      logs: bi('Browser network tab; GMS.Api listen ports', 'شبكة المتصفح؛ بورتات الاستماع'),
      customerMessage: bi('We hit an internal tools outage, not a problem with your gym name. Please wait a minute.', 'عطل أدوات داخلية، مش مشكلة في اسم النادي. استنوا دقيقة.'),
      closure: bi('Wizard moved to the contract step.', 'المعالج وصل لخطوة العقد.'),
      tech: bi('Vite VITE_API_PROXY_TARGET=https://localhost:5001/. AddPlatformCustomersCommerce must be applied; startup SeedAsync migrates.', 'البروكسي 5001. الهجرة بتتعمل مع SeedAsync.'),
    },
    {
      id: 'sales-cannot-issue',
      title: bi('Sales cannot issue a license', 'المبيعات مش قادرة تصدر ترخيص'),
      whatHappened: bi('Issue is hidden or 403. That is correct.', 'الإصدار مخفي أو 403. ده صح.'),
      doNot: bi('Do not share an Ops account. Do not paste a license key from another gym.', 'متشاركش حساب عمليات. ومتلصقش مفتاح من نادي تاني.'),
      immediate: bi('Finish customer + contract + payment. Open a Support ticket for Ops to issue against this customer/contract.', 'خلّص عميل وعقد ودفعة. افتح تذكرة للدعم عشان العمليات تصدر على العميل/العقد.'),
      recovery: bi('Ops uses Licenses → Issue or the onboard license step.', 'العمليات من التراخيص ← إصدار أو خطوة المعالج.'),
      escalation: bi('Escalate if Ops also gets 403 (policy mis-assigned).', 'صعّد لو العمليات كمان 403.'),
      logs: bi('Platform role on the user; 403 body', 'دور المنصة؛ جسم 403'),
      customerMessage: bi('Your purchase is recorded. Operations will issue the license next — sales cannot mint keys.', 'الشراء متسجل. العمليات هتصدر الترخيص — المبيعات مش بتعمل مفاتيح.'),
      closure: bi('License exists with CustomerId and ContractId.', 'الترخيص موجود مربوط بالعميل والعقد.'),
    },
  ],
  recovery: {
    en: 'If the wizard died mid-way, open the customer profile and continue from Contracts / Payments / Licenses. Do not create a duplicate customer.',
    ar: 'لو المعالج وقف في النص، افتح ملف العميل وكمل من العقود/الدفعات/التراخيص. متعملش عميل مكرر.',
  },
  escalation: {
    en: '404 after restart, 500 on customers table, or anyone asking to store a password on the customer.',
    ar: '404 بعد إعادة التشغيل، 500 على جدول العملاء، أو حد طالب تخزين كلمة سر على العميل.',
  },
  customerCommunication: {
    en: 'You are a HyMotion customer with a contract and (when Ops issues it) a Local license. The gym Desk on the PC is a separate login.',
    ar: 'أنتوا عميل HyMotion بعقد وترخيص محلي لما العمليات تصدره. مكتب النادي على الجهاز دخول منفصل.',
  },
  securityWarnings: [
    bi('Never store or generate gym owner passwords in the Platform Console.', 'متتخزنش ولا تولّد كلمات سر مالك النادي في لوحة المنصة.'),
    bi('Never paste license keys or JWT secrets into a public ticket.', 'متلصقش مفاتيح ترخيص أو JWT في تذكرة عامة.'),
    bi('Sales must not issue, revoke, reactivate, or transfer licenses.', 'المبيعات متصدرش ولا تسحب ولا تعيد ولا تنقل تراخيص.'),
  ],
  finalVerification: [
    bi('Customer + active contract + payment row', 'عميل + عقد نشط + صف دفعة'),
    bi('License issued by Ops and linked, or ticket waiting on Ops', 'ترخيص صادر من عمليات ومربوط، أو تذكرة مستنية العمليات'),
    bi('No password in the customer record', 'مفيش كلمة سر في سجل العميل'),
  ],
  closure: [
    bi('Customer created', 'العميل اتسجل'),
    bi('Contract active', 'العقد نشط'),
    bi('Payment recorded (or zero with a note)', 'الدفعة اتسجلت (أو صفر بملاحظة)'),
    bi('License linked or Ops ticket open', 'الترخيص مربوط أو تذكرة عمليات مفتوحة'),
    bi('Field kit / go-live next', 'الحقيبة / التشغيل الجاي'),
  ],
}

export const licenseLifecyclePlaybook: Playbook = {
  id: 'license-lifecycle',
  category: 'access',
  title: { en: 'Local license — issue, suspend, transfer', ar: 'الترخيص المحلي — إصدار، إيقاف، نقل' },
  purpose: {
    en: 'Operate Local licenses from Control Plane against a customer/contract. Crypto and activation stay as they are.',
    ar: 'شغّل التراخيص المحلية من لوحة التحكم مربوطة بعميل/عقد. التشفير والتفعيل زي ما هم.',
  },
  whenToUse: {
    en: 'New gym after a contract, replacement PC, suspend for non-payment, or revoke.',
    ar: 'نادي جديد بعد عقد، جهاز بديل، إيقاف لعدم الدفع، أو سحب.',
  },
  preconditions: [
    bi('Customer and (usually) an active contract already exist. See the onboard playbook.', 'العميل وعادة عقد نشط موجودين. شوف دليل التسجيل.'),
    bi('Caller is Ops or Admin. Sales may read the license, not change lifecycle.', 'اللي بينفّذ عمليات أو إدارة. المبيعات تقرأ الترخيص مش تغيّر دورته.'),
  ],
  requiredAccess: {
    en: 'PlatformOpsOrAbove for issue/suspend/revoke/reactivate/transfer. Reason text is required on destructive actions.',
    ar: 'عمليات فأعلى للإصدار والإيقاف والسحب والإعادة والنقل. نص سبب مطلوب على التدميري.',
  },
  risk: 'admin',
  audience: 'support',
  customerSummary: {
    en: 'Your license is tied to this gym PC. Moving PCs needs operations to authorize a transfer. We will not email private keys.',
    ar: 'الترخيص مربوط بجهاز النادي. نقل الجهاز محتاج تصريح من العمليات. مش هنبعت مفاتيح خاصة بالإيميل.',
  },
  steps: [
    {
      id: 'open',
      action: bi('Open Licenses. Prefer the customer profile Licenses tab so you do not issue against the wrong gym.', 'افتح التراخيص. فضّل تبويب التراخيص على ملف العميل عشان متصدرش على نادي غلط.'),
      who: 'hyMotion',
      expected: bi('List shows customer name snapshot, edition, status, installations.', 'القائمة فيها اسم العميل والإصدار والحالة والتثبيتات.'),
      verification: bi('You are looking at Local licenses, not a SaaS tenant subscription.', 'أنت على تراخيص محلي مش اشتراك سحابة.'),
      risk: 'safe',
      audience: 'support',
    },
    {
      id: 'issue',
      action: bi('Issue Lifetime (or the edition the contract bought) with device limit. Pass customerId and contractId.', 'أصدر مدى الحياة (أو الإصدار اللي العقد اشتراه) بحد أجهزة. مرّر customerId و contractId.'),
      who: 'hyMotion',
      expected: bi('Key shown per existing UI. Activation on the gym PC uses that key — not Control Plane login.', 'المفتاح يظهر زي الشاشة الحالية. التفعيل على جهاز النادي بالمفتاح — مش دخول اللوحة.'),
      verification: bi('Customer profile shows the license. Signing still uses the existing CustomerName snapshot.', 'ملف العميل فيه الترخيص. التوقيع لسه بيستخدم لقطة الاسم.'),
      risk: 'admin',
      audience: 'support',
      tech: bi('POST /platform-api/local-licenses. Do not change LicenseSigning keys in a playbook. DeviceLimit is on the license row.', 'POST local-licenses. متلعبش في مفاتيح التوقيع من الدليل. DeviceLimit على الصف.'),
    },
    {
      id: 'suspend',
      action: bi('Suspend or revoke only with a written reason (Ops UI enforces a minimum length). Sales cannot do this.', 'إيقاف أو سحب بسبب مكتوب (الشاشة بتفرض طول أدنى). المبيعات تقدرش.'),
      who: 'hyMotion',
      expected: bi('Gym PC will fail validation on next check. Tell the owner before you click.', 'جهاز النادي هيفشل التحقق في الفحص الجاي. قول للمالك قبل ما تضغط.'),
      verification: bi('Status on the license detail. Audit event exists.', 'الحالة على تفاصيل الترخيص. فيه حدث تدقيق.'),
      risk: 'destructive',
      audience: 'support',
    },
    {
      id: 'transfer',
      action: bi('Replacement PC: Authorize transfer on the old installation, then activate the same license on the new PC after restore. Do not issue a second lifetime key unless Ops decided the old one is revoked.', 'جهاز بديل: صرّح بالنقل على التثبيت القديم، بعدين فعّل نفس الترخيص على الجهاز الجديد بعد الاستعادة. متصدرش مفتاح مدى حياة تاني إلا لو العمليات سحبت القديم.'),
      who: 'hyMotion',
      expected: bi('Transfer count increases. Old installation is no longer the active slot if the product moved it.', 'عدد النقل يزيد. التثبيت القديم مش الفتحة النشطة لو المنتج نقله.'),
      verification: bi('New installation shows after the gym PC activates. Restore playbook case 17 if the disk died.', 'تثبيت جديد بعد تفعيل جهاز النادي. حالة 17 في دليل الاستعادة لو القرص مات.'),
      risk: 'destructive',
      audience: 'support',
      tech: bi('POST /platform-api/local-licenses/{id}/authorize-transfer { oldInstallationId, reason }. Ops/Admin. Then on-box activation as today.', 'authorize-transfer. بعدين التفعيل على الجهاز زي دلوقتي.'),
    },
  ],
  failures: [
    {
      id: 'sales-403',
      title: bi('403 on issue or transfer', '403 على الإصدار أو النقل'),
      whatHappened: bi('Role is Sales or Support. Lifecycle writes are Ops/Admin.', 'الدور مبيعات أو دعم. كتابة الدورة للعمليات/الإدارة.'),
      doNot: bi('Do not mint a key in a spreadsheet.', 'متعملش مفتاح في شيت.'),
      immediate: bi('Hand the customer id to Ops. Sales can still record payments.', 'سلّم رقم العميل للعمليات. المبيعات تقدر تسجّل دفعات.'),
      recovery: bi('Ops signs in and retries.', 'العمليات تدخل وتعيد.'),
      escalation: bi('Escalate a Support user who was told they can issue licenses — they cannot.', 'صعّد لو حد من الدعم اتقله إنه يقدر يصدر — مش يقدر.'),
      logs: bi('403; user role', '403؛ الدور'),
      customerMessage: bi('License changes are done by operations, not by the salesperson.', 'تغيير الترخيص عند العمليات مش المبيعات.'),
      closure: bi('Ops completed the action or declined with a reason.', 'العمليات خلصت أو رفضت بسبب.'),
    },
  ],
  recovery: {
    en: 'Wrong gym: do not transfer blindly — open the customer first. Wrong PC: restore data then activate.',
    ar: 'نادي غلط: متنقلش بعشوائية — افتح العميل الأول. جهاز غلط: استعد البيانات بعدين فعّل.',
  },
  escalation: {
    en: 'Device limit exceeded, stolen PC without transfer, or anyone asking for the signing private key.',
    ar: 'تجاوز حد الأجهزة، جهاز مسروق من غير نقل، أو حد طالب المفتاح الخاص للتوقيع.',
  },
  customerCommunication: {
    en: 'We will tell you when the license is active on this PC. Keep your USB backup; a new PC starts empty.',
    ar: 'هنقول امتى الترخيص نشط على الجهاز. احتفظوا بنسخة USB؛ الجهاز الجديد بيبدأ فاضي.',
  },
  securityWarnings: [
    bi('Do not send PEM private keys, license files from ProgramData, or JWT secrets in chat.', 'متبعتش مفاتيح PEM أو ملفات ترخيص من ProgramData أو JWT في الشات.'),
  ],
  finalVerification: [
    bi('License linked to the intended customer/contract', 'الترخيص مربوط بالعميل/العقد المقصود'),
    bi('Installations match the live PC', 'التثبيتات تطابق الجهاز الحي'),
  ],
  closure: [
    bi('Action audited', 'الإجراء متسجل'),
    bi('Owner told the status', 'المالك اتعرف الحالة'),
    bi('Case closed', 'الحالة اتقفلت'),
  ],
}

export const supportTicketPlaybook: Playbook = {
  id: 'support-ticket',
  category: 'support',
  title: { en: 'Support ticket on a customer', ar: 'تذكرة دعم على عميل' },
  purpose: {
    en: 'Open and update Control Plane support tickets linked to a customer (and optionally contract, license, installation). This is not the gym Desk inbox.',
    ar: 'افتح وحدّث تذاكر دعم لوحة التحكم مربوطة بعميل (واختياري عقد/ترخيص/تثبيت). دي مش صندوق وارد مكتب النادي.',
  },
  whenToUse: {
    en: 'Install blocked, license question, printer/PVC, backup/restore, or Sales waiting on Ops to issue a key.',
    ar: 'تثبيت واقف، سؤال ترخيص، طابعة/PVC، نسخ/استعادة، أو مبيعات مستنية العمليات تصدر مفتاح.',
  },
  preconditions: [bi('Customer exists. Do not open a ticket with only a license key and no customer.', 'العميل موجود. متفتحش تذكرة بمفتاح ترخيص من غير عميل.')],
  requiredAccess: {
    en: 'PlatformCustomerAccess can read/create. Updates follow the existing ticket API (status/priority/assignee/resolution).',
    ar: 'صلاحية وصول العملاء تقرأ وتنشئ. التحديث حسب API التذكرة (حالة/أولوية/مسؤول/حل).',
  },
  risk: 'safe',
  audience: 'support',
  customerSummary: {
    en: 'We logged your issue on your HyMotion customer file. We still may need someone at the gym PC for backup or restore.',
    ar: 'سجّلنا المشكلة على ملف عميل HyMotion. لسه ممكن نحتاج حد على جهاز النادي للنسخ أو الاستعادة.',
  },
  steps: [
    {
      id: 'open',
      action: bi('Customers → the gym → Support, or Support tickets. Create with a real subject. Link license/installation when the PC is involved.', 'العملاء ← النادي ← الدعم، أو تذاكر الدعم. أنشئ بموضوع حقيقي. اربط الترخيص/التثبيت لو الجهاز طرف.'),
      who: 'support',
      expected: bi('Ticket number HY-SUP-yyyy-0000. Customer name visible.', 'رقم تذكرة HY-SUP-yyyy-0000. اسم العميل ظاهر.'),
      verification: bi('Profile open-ticket count increased. No secrets in the description.', 'عدد التذاكر المفتوحة زاد. مفيش أسرار في الوصف.'),
      risk: 'safe',
      audience: 'support',
      tech: bi('POST /platform-api/support-tickets. PATCH for status. Do not use SaaS tenant risk-queue as a Local gym ticket.', 'POST support-tickets. متستخدمش طابور مخاطر السحابة كتذكرة نادي محلي.'),
    },
    {
      id: 'work',
      action: bi('Follow the matching playbook (field kit, backup, restore, license, PVC). Paste only Copy-command output the owner already allowed — never passwords.', 'امشي الدليل المطابق (حقيبة، نسخ، استعادة، ترخيص، PVC). الصق مخرجات الأوامر اللي المالك سمح بيها — عمرك كلمات سر.'),
      who: 'support',
      expected: bi('Ticket status moves. Resolution is written in plain language.', 'حالة التذكرة بتتحرك. الحل مكتوب بلغة بسيطة.'),
      verification: bi('Customer informed. Closure on this playbook UI is still a human tick — the ticket API does not auto-close cases.', 'العميل اتعرف. الإغلاق هنا علامة بشرية — الـ API مش بيقفل الحالات لوحده.'),
      risk: 'safe',
      audience: 'both',
    },
  ],
  failures: [],
  recovery: { en: 'Wrong customer: open a new ticket on the right profile; do not edit history to swap gyms.', ar: 'عميل غلط: افتح تذكرة على الملف الصح؛ متعدلش التاريخ عشان تبدّل نوادي.' },
  escalation: { en: 'Data-loss, stolen PC, or license private-key requests.', ar: 'فقدان بيانات، جهاز مسروق، أو طلب مفتاح ترخيص خاص.' },
  customerCommunication: { en: 'Your ticket number is HY-SUP-…. We will say if we need you at the PC.', ar: 'رقم التذكرة HY-SUP-…. هنقول لو محتاجينكم على الجهاز.' },
  securityWarnings: [bi('No passwords, OTPs, .bak files, or PEM keys in the ticket body.', 'مفيش كلمات سر أو OTP أو .bak أو PEM في نص التذكرة.')],
  finalVerification: [bi('Ticket linked to the correct customer', 'التذكرة على العميل الصح')],
  closure: [bi('Ticket resolved or closed', 'التذكرة اتحلّت أو اتقفلت'), bi('Owner informed', 'المالك اتعرف')],
}
