import type { Playbook } from '../types'
import { bi } from '../i18n'

/** Gym-facing Local install. Same shape as any Windows desktop app (Git, Chrome, …). */
export const localDesktopPlaybook: Playbook = {
  id: 'local-desktop-setup',
  category: 'setup',
  title: { en: 'Install HyMotion on this PC', ar: 'ثبّت HyMotion على الجهاز ده' },
  purpose: {
    en: 'Install HyMotion Local the way you install any Windows program: open Setup, click Next until Finish, then open the desktop icon.',
    ar: 'ثبّت HyMotion المحلي زي أي برنامج ويندوز: افتح الإعداد، دوّس التالي لحد ما تخلّص، بعدين افتح أيقونة سطح المكتب.',
  },
  whenToUse: {
    en: 'First time on this gym PC. You have HyMotionSetup (USB or a file HyMotion sent).',
    ar: 'أول مرة على جهاز النادي. معاك HyMotionSetup (فلاشة أو ملف من HyMotion).',
  },
  preconditions: [
    bi('This is a Windows PC at the gym. You do not need Administrator.', 'ده جهاز ويندوز في النادي. مش محتاج صلاحية مسؤول.'),
    bi('You do not need to type commands. If Setup asks for something you do not understand, tap I need help.', 'مش محتاج تكتب أوامر. لو الإعداد طلب حاجة مش فاهمها، اضغط محتاج مساعدة.'),
  ],
  requiredAccess: {
    en: 'Someone sitting at the gym PC. You do not need admin rights.',
    ar: 'حد قاعد على جهاز النادي. مش محتاج صلاحية أدمن.',
  },
  risk: 'safe',
  audience: 'both',
  customerSummary: {
    en: 'Double-click Setup. Click Next until Finish. Then open HyMotion from the desktop. That is the whole install.',
    ar: 'دبل كليك على الإعداد. دوّس التالي لحد ما تخلّص. بعدين افتح HyMotion من سطح المكتب. ده كل التثبيت.',
  },
  lifecycle: [
    bi('Find Setup', 'لاقي الإعداد'),
    bi('Next until Finish', 'التالي لحد ما تخلّص'),
    bi('Open HyMotion', 'افتح HyMotion'),
    bi('Sign in', 'ادخل'),
  ],
  steps: [
    {
      id: 'find',
      action: bi('Plug in the USB HyMotion gave you, or open the folder with the install file. Find HyMotionSetup (a blue/setup icon). Do not open files named Launcher or Backup yet.', 'ركّب الفلاشة اللي HyMotion ادّاهالك، أو افتح المجلد اللي فيه ملف التثبيت. لاقي HyMotionSetup (أيقونة إعداد). متفتحش Launcher أو Backup دلوقتي.'),
      who: 'customer',
      expected: bi('You see HyMotionSetup.', 'شايف HyMotionSetup.'),
      verification: bi('The name is HyMotionSetup. If you only see folders, tap I need help.', 'الاسم HyMotionSetup. لو شايف مجلدات بس، اضغط محتاج مساعدة.'),
      risk: 'safe',
      audience: 'both',
    },
    {
      id: 'run',
      action: bi('Double-click HyMotionSetup. If Windows SmartScreen hides the file, click More info → Run anyway only if HyMotion gave you this USB.', 'دبل كليك HyMotionSetup. لو ويندوز خبّى الملف، اضغط المزيد ← تشغيل على أي حال بس لو HyMotion هو اللي ادّى الفلاشة.'),
      who: 'customer',
      expected: bi('A setup window opens. It looks like other Windows installers (Next / Finish).', 'نافذة إعداد تفتح. شكلها زي أي مثبّت ويندوز (التالي / إنهاء).'),
      verification: bi('You are inside Setup, not on a website.', 'أنت جوه الإعداد، مش على موقع.'),
      failurePath: bi('If Windows hides the file, click More info → Run anyway only if HyMotion gave you this USB.', 'لو ويندوز خبّى الملف، اضغط المزيد ← تشغيل على أي حال بس لو HyMotion هو اللي ادّى الفلاشة.'),
      risk: 'safe',
      audience: 'both',
    },
    {
      id: 'next',
      action: bi('Click Next (or التالي) until you see Finish (or إنهاء). Leave the ticks as they are. Wait if the bar is moving. Do not close the window.', 'دوّس التالي لحد ما تشوف إنهاء. سيب العلامات زي ما هي. استنى لو الخط بيتحرك. متقفلش النافذة.'),
      who: 'customer',
      expected: bi('Setup says it finished. You can click Finish.', 'الإعداد يقول خلّص. تقدر تضغط إنهاء.'),
      verification: bi('The setup window closed after Finish. You did not download extra programs from the internet.', 'نافذة الإعداد اتقفلت بعد إنهاء. منزلتش برامج زيادة من النت.'),
      failurePath: bi('If Setup stops, tap I need help. Do not install random downloads.', 'لو الإعداد وقف، اضغط محتاج مساعدة. متثبّتش تحميلات عشوائية.'),
      risk: 'safe',
      audience: 'both',
    },
    {
      id: 'open',
      action: bi('On the desktop, double-click HyMotion (the daily icon — not Setup, not Backup).', 'على سطح المكتب، دبل كليك HyMotion (أيقونة كل يوم — مش الإعداد، مش النسخ).'),
      who: 'customer',
      expected: bi('HyMotion opens. You see a sign-in page or a first-time gym screen.', 'HyMotion يفتح. تشوف دخول أو شاشة تجهيز النادي أول مرة.'),
      verification: bi('The window is HyMotion. If nothing appears, search the Start menu for HyMotion. If still missing, tap I need help.', 'النافذة HyMotion. لو مفيش حاجة، دور في قائمة ابدأ. لو برضه مش موجود، اضغط محتاج مساعدة.'),
      risk: 'safe',
      audience: 'both',
    },
    {
      id: 'signin',
      action: bi('Finish the first-time screens if they appear, then sign in with the owner account HyMotion gave you. Do not type the password into WhatsApp or email.', 'خلّص شاشات أول مرة لو ظهرت، بعدين ادخل بحساب المالك اللي HyMotion ادّاهولك. متكتبش كلمة السر في واتساب أو إيميل.'),
      who: 'owner',
      expected: bi('You reach the gym home screen.', 'وصلت لشاشة النادي الرئيسية.'),
      verification: bi('You can see members or the home tiles. Staff setup and printers come later — not now.', 'شايف الأعضاء أو مربعات الرئيسية. الموظفين والطابعات بعدين — مش دلوقتي.'),
      risk: 'safe',
      audience: 'both',
    },
  ],
  failures: [
    {
      id: 'windows-blocked',
      title: bi('Windows blocked Setup', 'ويندوز منع الإعداد'),
      whatHappened: bi('Windows SmartScreen or antivirus hid or blocked HyMotionSetup.', 'ويندوز أو الأنتي فيرس خبّى أو منع HyMotionSetup.'),
      doNot: bi('Do not download a second installer from a random website.', 'متنزّلش مثبّت تاني من موقع عشوائي.'),
      immediate: bi('Click More info → Run anyway only on the file from the HyMotion USB. Or tap I need help.', 'اضغط المزيد ← تشغيل على أي حال بس على ملف فلاشة HyMotion. أو اضغط محتاج مساعدة.'),
      recovery: bi('HyMotion support confirms the file, then you try Setup again.', 'دعم HyMotion يأكد الملف، بعدين تعيد الإعداد.'),
      escalation: bi('Antivirus keeps deleting Setup.', 'الأنتي فيرس بيمسح الإعداد.'),
      logs: bi('Windows message text, photographed if needed.', 'نص رسالة ويندوز، صورة لو لزم.'),
      customerMessage: bi('Use the HyMotion file we gave you. If Windows SmartScreen hides it, More info → Run anyway. Do not download another copy from the internet.', 'استخدم ملف HyMotion اللي ادّيناهولك. لو ويندوز خبّاه، المزيد ← تشغيل على أي حال. متنزّلش نسخة من النت.'),
      closure: bi('Setup window opened.', 'نافذة الإعداد اتفتحت.'),
    },
    {
      id: 'setup-stopped',
      title: bi('Setup stopped in the middle', 'الإعداد وقف في النص'),
      whatHappened: bi('The installer asked for something extra (often a database) or closed with an error.', 'المثبّت طلب حاجة زيادة (غالبًا قاعدة بيانات) أو اتقفل بخطأ.'),
      doNot: bi('Do not install extra programs from Google. Do not type commands from chat.', 'متثبّتش برامج زيادة من جوجل. ومتكتبش أوامر من الشات.'),
      immediate: bi('Photograph the screen. Tap I need help. Wait for HyMotion.', 'صوّر الشاشة. اضغط محتاج مساعدة. استنى HyMotion.'),
      recovery: bi('HyMotion support continues from this PC. They may run Setup again after they fix the stop.', 'دعم HyMotion يكمّل من الجهاز. ممكن يعيد الإعداد بعد ما يصلّح الوقفة.'),
      escalation: bi('Setup fails twice with the same message.', 'الإعداد فشل مرتين بنفس الرسالة.'),
      logs: bi('Photo of the Setup error.', 'صورة خطأ الإعداد.'),
      customerMessage: bi('Leave the PC as it is. We will finish the install with you. Please do not add extra programs.', 'سيب الجهاز زي ما هو. هنخلّص التثبيت معاك. متزودش برامج.'),
      closure: bi('HyMotion opens from the desktop icon.', 'HyMotion بيفتح من أيقونة سطح المكتب.'),
      tech: bi('Usual cause: SQL Express missing. Support uses the field-kit SQL steps, then re-runs HyMotionSetup.exe. Do not paste Restore-HyMotion.ps1 as an install.', 'السبب الغالب: SQL Express مش موجود. الدعم يستخدم خطوات SQL في الحقيبة، بعدين يعيد HyMotionSetup.exe. متلصقش سكربت الاستعادة كتثبيت.'),
    },
    {
      id: 'no-icon',
      title: bi('No HyMotion icon after Finish', 'مفيش أيقونة HyMotion بعد إنهاء'),
      whatHappened: bi('Setup closed but the desktop has no HyMotion shortcut.', 'الإعداد قفل وسطح المكتب من غير اختصار HyMotion.'),
      doNot: bi('Do not run Setup a second time immediately.', 'متشغّلش الإعداد تاني على طول.'),
      immediate: bi('Open the Start menu and search HyMotion. If it is there, pin it. If not, tap I need help.', 'افتح قائمة ابدأ ودور HyMotion. لو موجود، ثبّته. لو لأ، اضغط محتاج مساعدة.'),
      recovery: bi('Support checks that Setup finished and that HyMotionLauncher is installed.', 'الدعم يتأكد إن الإعداد خلّص وإن Launcher موجود.'),
      escalation: bi('Start menu has Setup only, no HyMotion.', 'قائمة ابدأ فيها الإعداد بس من غير HyMotion.'),
      logs: bi('Desktop screenshot.', 'صورة سطح المكتب.'),
      customerMessage: bi('Search the Start menu for HyMotion. If you only see Setup, wait for us — do not keep clicking Setup.', 'دور في قائمة ابدأ على HyMotion. لو شايف الإعداد بس، استنانا — متفضلش تضغط إعداد.'),
      closure: bi('HyMotion opens from Start or the desktop.', 'HyMotion بيفتح من ابدأ أو سطح المكتب.'),
    },
  ],
  recovery: {
    en: 'If Setup did not finish, leave the PC and wait for HyMotion. Do not invent extra installs.',
    ar: 'لو الإعداد ما خلّصش، سيب الجهاز واستنى HyMotion. متخترعش تثبيتات زيادة.',
  },
  escalation: {
    en: 'Windows keeps blocking the file, or Setup names SQL / a missing program.',
    ar: 'ويندوز بيفضل يمنع الملف، أو الإعداد بيسمّي SQL / برنامج ناقص.',
  },
  customerCommunication: {
    en: 'Install is Setup → Next → Finish → desktop icon. We will not ask you to paste commands.',
    ar: 'التثبيت = إعداد ← التالي ← إنهاء ← أيقونة سطح المكتب. مش هنطلب منك لصق أوامر.',
  },
  securityWarnings: [
    bi('Never paste the owner password into chat.', 'متلصقش كلمة سر المالك في الشات.'),
    bi('Use only the USB or file HyMotion gave you.', 'استخدم الفلاشة أو الملف اللي HyMotion ادّاه بس.'),
  ],
  finalVerification: [
    bi('HyMotion opens from the desktop', 'HyMotion بيفتح من سطح المكتب'),
    bi('Owner signed in', 'المالك دخل'),
  ],
  closure: [
    bi('Setup finished', 'الإعداد خلّص'),
    bi('Desktop icon opens HyMotion', 'أيقونة سطح المكتب بتفتح HyMotion'),
    bi('Owner signed in', 'المالك دخل'),
  ],
}
