import type { Playbook } from '../types'
import { bi } from '../i18n'

export const setupPlaybook: Playbook = {
  id: 'new-gym-setup',
  category: 'setup',
  title: { en: 'New customer / new gym setup', ar: 'عميل جديد / تجهيز نادي' },
  purpose: {
    en: 'Install and check a new gym on what the product actually has today: HyMotion Local on a PC, and/or a cloud gym in the Control Plane.',
    ar: 'ثبّت وتأكد نادي جديد على اللي المنتج فيه النهارده: HyMotion المحلي على جهاز، و/أو نادي سحابي في لوحة التحكم.',
  },
  whenToUse: { en: 'Every new gym or replacement install.', ar: 'كل نادي جديد أو تثبيت بديل.' },
  preconditions: [
    bi('Customer + contract exist in Control Plane (Onboard customer playbook). Ops/Admin issues the Local license — Sales cannot.', 'العميل والعقد موجودين في لوحة التحكم (دليل تسجيل العميل). العمليات/الإدارة تصدر الترخيص المحلي — المبيعات تقدرش.'),
  ],
  requiredAccess: {
    en: 'Platform Ops/Admin for licenses and SaaS provision. A Windows user on the gym PC for Local Setup (Administrator not required).',
    ar: 'عمليات المنصة للتراخيص والتوفير السحابي. مستخدم ويندوز على جهاز النادي للتثبيت المحلي (مش محتاج مسؤول).',
  },
  risk: 'admin',
  audience: 'support',
  customerSummary: {
    en: 'Gym people use Install HyMotion on this PC (Setup → Next → Finish). This list is the HyMotion team checklist around that installer.',
    ar: 'ناس النادي يستخدموا ثبّت HyMotion على الجهاز ده (إعداد ← التالي ← إنهاء). القائمة دي تشيك ليست الفريق حوالين المثبّت.',
  },
  lifecycle: [
    bi('Customer', 'عميل'),
    bi('Setup', 'تجهيز'),
    bi('Configure', 'ضبط'),
    bi('Verify', 'تحقق'),
    bi('Go live', 'تشغيل'),
    bi('Support handover', 'تسليم الدعم'),
  ],
  steps: [
    { id: 'desktop-first', action: bi('On the gym PC, install is HyMotionSetup.exe like any desktop app: Next until Finish, then the HyMotion desktop icon. Do not start the visit with SQL or PowerShell. Gym people follow playbook local-desktop-setup.', 'على جهاز النادي التثبيت هو HyMotionSetup.exe زي أي برنامج: التالي لحد إنهاء، بعدين أيقونة HyMotion. متبدأش الزيارة بـ SQL أو PowerShell. ناس النادي على دليل local-desktop-setup.'), who: 'support', expected: bi('Owner never saw a black command window. Setup finished or you photographed the stop.', 'المالك مشافش شاشة أوامر سودا. الإعداد خلّص أو صورت الوقفة.'), verification: bi('Desktop icon opens HyMotion, or Something went wrong is open.', 'أيقونة سطح المكتب بتفتح HyMotion، أو حاجة وقفت مفتوحة.'), risk: 'safe', audience: 'support' },
    { id: 'confirmed', action: bi('Finish Control Plane onboard first: Customer → Contract → Payment. See playbook customer-onboard.', 'خلّص تسجيل لوحة التحكم الأول: عميل ← عقد ← دفعة. شوف دليل customer-onboard.'), who: 'hyMotion', expected: bi('Customer profile exists. Contract is active. Payment row matches cash/transfer actually received.', 'ملف العميل موجود. العقد نشط. صف الدفعة يطابق الكاش/التحويل اللي دخل.'), verification: bi('Customers list shows the gym. Purchases tab lists SKUs (software, install, PVC, printer).', 'قائمة العملاء فيها النادي. تبويب المشتريات فيه الأصناف.'), risk: 'safe', audience: 'support' },
    { id: 'info', action: bi('Ops/Admin: issue the Local license against that customer and contract. Sales must not issue. SaaS: provision tenant separately and set TenantId on the customer if you use it.', 'عمليات/إدارة: أصدر الترخيص المحلي على العميل والعقد. المبيعات متصدرش. السحابة: وفّر الصالة لوحدها واربط TenantId على العميل لو بتستخدمه.'), who: 'hyMotion', expected: bi('License key issued (Ops/Admin) with CustomerId/ContractId. SaaS: Provision gym wizard (business, owner, plan, trial).', 'مفتاح ترخيص اتصادر (عمليات) مربوط بالعميل/العقد. سحابة: معالج توفير الصالة.'), verification: bi('Customer profile Licenses tab shows the key’s license. Tenants list shows a SaaS gym if that edition.', 'تبويب التراخيص على العميل فيه الترخيص. قائمة الصالات فيها السحابة لو الإصدار ده.'), risk: 'admin', audience: 'support' },
    { id: 'commercial', action: bi('Do not keep the deal only in chat. The contract and catalog snapshots in Control Plane are the commercial record. Contract ≠ invoice. License ≠ customer.', 'متسيبش الاتفاق في الشات بس. العقد ولقطات الكتالوج في اللوحة هي السجل التجاري. العقد ≠ فاتورة. الترخيص ≠ العميل.'), who: 'hyMotion', expected: bi('HY-CTR-… number exists. SKUs match what will be installed (Local software, PVC, printer, install service).', 'رقم HY-CTR-… موجود. الأصناف تطابق اللي هيتثبت (برنامج محلي، PVC، طابعة، تركيب).'), verification: bi('Payments tab is honest (unpaid / partial / paid). No owner password stored.', 'تبويب الدفعات صادق (غير مدفوع / جزئي / مدفوع). مفيش كلمة سر مالك متخزنة.'), risk: 'safe', audience: 'support' },
    { id: 'edition', action: bi('Product: HyMotion Local Lifetime (installer + license) and/or SaaS tenant (Control Plane).', 'المنتج: محلي مدى الحياة و/أو صالة سحابية.'), who: 'hyMotion', expected: bi('Do not mix Local backup into SaaS. Backup & Recovery 404s on cloud Desk.', 'متخلطش نسخ المحلي في السحابة. صفحة النسخ بتختفي هناك.'), verification: bi('Edition written on the case.', 'الإصدار مكتوب على الحالة.'), risk: 'safe', audience: 'support' },
    { id: 'field-kit', action: bi('Local: pack the support USB/SSD first. Open the Field kit playbook. Prefer HyMotionSetup.exe at the kit root — do not make PowerShell the gym-visit path.', 'المحلي: جهّز USB/SSD الدعم الأول. افتح دليل الحقيبة. فضّل HyMotionSetup.exe في جذر الحقيبة — متخلّيش PowerShell طريق زيارة النادي.'), who: 'support', expected: bi('Folders 01–05 exist. SQL Express installer, GMS.Api.exe, HyMotionSetup.exe, HyMotionLauncher.exe, HyMotionBackup.exe are on the disk.', 'مجلدات 01–05 موجودة. مثبّت SQL و GMS.Api.exe و HyMotionSetup و Launcher و Backup على الديسك.'), verification: bi('Open /ops-playbooks/field-kit-usb and tick the pack-phase closure items.', 'افتح دليل الحقيبة وعلّم بنود التجهيز.'), risk: 'admin', audience: 'support' },
    { id: 'pc-req', action: bi('Local: Windows 64-bit with SQL Server Express (or local SQL). Cloud: a browser that can reach the cloud API.', 'المحلي: ويندوز 64 و SQL Express. السحابة: متصفح يوصل للـ API.'), who: 'support', expected: bi('The installer checks SQL before it copies program files.', 'المثبّت يفحص SQL قبل ما ينسخ ملفات البرنامج.'), verification: bi('SQL accepts this Windows user’s sign-in. That user owns the gym database only — not the whole SQL server.', 'SQL يقبل دخول المستخدم ده. المستخدم هيتملك قاعدة النادي بس — مش SQL كله.'), risk: 'safe', audience: 'support', tech: bi('Installer calls Test-SqlServerAvailability.ps1 -WriteConfig -ServiceAccount <current user> -ConfigRoot %LOCALAPPDATA%\\HyMotion. Grant is db_owner on HyMotionLocal. Never sysadmin.', 'المثبّت يستدعي Test-SqlServerAvailability.ps1. الصلاحية db_owner على HyMotionLocal للمستخدم الحالي. مش sysadmin.') },
    { id: 'package', action: bi('On the build PC: publish-local.ps1 and/or build-desktop.ps1 so publish-local has GMS.Api.exe plus HyMotionSetup.exe, HyMotionLauncher.exe, HyMotionBackup.exe. Inno HyMotionLocalSetup-1.1.0.exe is optional and not verified in every office.', 'على جهاز البناء: publish-local و/أو build-desktop عشان المجلد فيه GMS.Api ومعاه Setup و Launcher و Backup. ملف Inno اختياري ومش متحقَّق في كل مكتب.'), who: 'support', expected: bi('Team install = double-click HyMotionSetup.exe (this Windows user, no Administrator). Daily gym use = HyMotion desktop icon (Launcher). Owner backup/restore = HyMotion Backup.', 'تثبيت الفريق = دبل كليك HyMotionSetup (مستخدم الجهاز، من غير مسؤول). الاستخدام اليومي = أيقونة HyMotion (Launcher). نسخ/استعادة المالك = HyMotion Backup.'), verification: bi('If using a folder publish, confirm install-scripts\\backup exists next to GMS.Api.exe.', 'لو نشر مجلد، أكد وجود سكربتات النسخ جنب الـ exe.'), risk: 'admin', audience: 'support' },
    { id: 'sql', action: bi('Local: let Setup (or the SQL check script) create the gym database and give this Windows user rights on it.', 'المحلي: خلّي الإعداد (أو سكربت فحص SQL) ينشئ قاعدة النادي ويدّي المستخدم ده صلاحية عليها.'), who: 'support', expected: bi('Config file for this Windows user points at database HyMotionLocal.', 'ملف الإعداد للمستخدم ده بيشير لقاعدة HyMotionLocal.'), verification: bi('After Setup, the desktop icon can open the database.', 'بعد الإعداد، أيقونة سطح المكتب تقدر تفتح القاعدة.'), risk: 'safe', audience: 'support', tech: bi('Test-SqlServerAvailability.ps1 -WriteConfig -ConfigRoot %LOCALAPPDATA%\\HyMotion. File typically %LOCALAPPDATA%\\HyMotion\\config\\appsettings.json Server=.;Database=HyMotionLocal. Launcher sets ASPNETCORE_ENVIRONMENT=Local.', 'السكربت -WriteConfig. الملف appsettings.json عادة تحت LocalAppData. Launcher يضبط البيئة Local.') },
    { id: 'installed', action: bi('Double-click HyMotionSetup as a normal Windows user, then open the HyMotion desktop icon. Registering a Windows service is optional and only if you need HyMotion at boot with nobody signed in.', 'دبل كليك HyMotionSetup كمستخدم ويندوز عادي، بعدين افتح أيقونة HyMotion. تسجيل خدمة ويندوز اختياري وبس لو محتاج HyMotion مع بداية الجهاز من غير ما حد يدخل.'), who: 'support', expected: bi('HyMotion is running. The browser can open the gym on this PC.', 'HyMotion شغال. المتصفح يقدر يفتح النادي على الجهاز.'), verification: bi('http://localhost:7140/health returns 200. A Windows service named HyMotion is not required.', 'مسار الصحة 200. خدمة ويندوز HyMotion مش مطلوبة.'), risk: 'safe', audience: 'support', tech: bi('User-mode: GMS.Api.exe from %LOCALAPPDATA%\\HyMotion\\app. Optional: install-service.ps1 -InstallDir <folder> as Administrator (NETWORK SERVICE, ASPNETCORE_ENVIRONMENT=Local).', 'وضع المستخدم: GMS.Api من LocalAppData. اختياري: install-service.ps1 كمسؤول.'), commands: [
      { id: 'health', label: bi('Health check', 'فحص الصحة'), text: 'Invoke-WebRequest http://localhost:7140/health -UseBasicParsing', supportOnly: true },
    ] },
    { id: 'tenant-local', action: bi('Local first-run: complete on-box gym/owner setup as the product presents it. SaaS: owner email from provision wizard.', 'المحلي: تجهيز النادي/المالك كما يظهر المنتج. السحابة: إيميل المالك من المعالج.'), who: 'owner', expected: bi('Owner can sign in on the Desk.', 'المالك يقدر يدخل المكتب.'), verification: bi('Login page accepts the owner.', 'صفحة الدخول تقبل المالك.'), risk: 'safe', audience: 'both' },
    { id: 'roles', action: bi('Desk Administration → Staff and Roles (OwnerOnly). Assign least privilege.', 'المكتب ← موظفون وأدوار. أقل صلاحية.'), who: 'owner', expected: bi('Staff can only see what their permissions allow.', 'الموظف يشوف صلاحياته بس.'), verification: bi('A cashier cannot open Backup & Recovery (OwnerOnly).', 'الكاشير يفتحش النسخ (للمالك بس).'), risk: 'safe', audience: 'both' },
    { id: 'branding', action: bi('Gym name appears in the Desk chrome. Dedicated branding studio is not a separate installer step.', 'اسم النادي يظهر في إطار المكتب. مفيش استوديو علامة كخطوة تثبيت منفصلة.'), who: 'owner', expected: bi('Name correct in the top bar.', 'الاسم صح في الشريط.'), verification: bi('Owner confirms.', 'المالك يأكد.'), risk: 'safe', audience: 'both' },
    { id: 'printer', action: bi('Receipt printer: Windows print from Sale/Invoices. PVC card printer: see Access cards playbook — gym-branded blanks, no HyMotion-as-gym. No separate HyMotion printer wizard.', 'طابعة الإيصال: طباعة ويندوز من البيع/الفواتير. طابعة PVC: دليل كروت الدخول — كروت بعلامة النادي، مش HyMotion كنادي. مفيش معالج طابعة في HyMotion.'), who: 'staffOnPc', expected: bi('One receipt and/or one PVC blank, or N/A if this gym is paperless.', 'إيصال و/أو كرت PVC فاضي، أو غير منطبق لو النادي من غير ورق.'), verification: bi('Owner OK, or N/A on the case.', 'موافقة المالك أو غير منطبق.'), risk: 'safe', audience: 'both' },
    { id: 'barcode', action: bi('If PVC cards were sold: assign AccessCard.Code and scan at attendance. MemberNumber is not the PVC barcode.', 'لو كروت PVC اتباعت: عيّن AccessCard.Code وامسح في الحضور. رقم العضو مش باركود الـ PVC.'), who: 'staffOnPc', expected: bi('One member scans in with the card, or N/A.', 'عضو يدخل بالكرت، أو غير منطبق.'), verification: bi('See access-cards-pvc playbook.', 'شوف دليل كروت PVC.'), risk: 'safe', audience: 'both' },
    { id: 'backup-cfg', action: bi('Local only: Administration → Backup & Recovery. Owner clicks Save a copy now. Register nightly task if the page says not scheduled.', 'المحلي بس: الإدارة ← النسخ. المالك يضغط احفظ نسخة دلوقتي. سجّل المهمة الليلية لو الصفحة بتقول مش متجدولة.'), who: 'support', expected: bi('Looks good / Healthy history row. Task HyMotion Nightly Backup if installer/register ran.', 'صف تمام/سليم. مهمة ليلية لو التسجيل تم.'), verification: bi('See Backup playbook. SaaS: this page 404s — mark N/A.', 'شوف دليل النسخ. السحابة: الصفحة 404 — غير منطبق.'), risk: 'admin', audience: 'support' },
    { id: 'restore-ready', action: bi('Show the owner Open Restore (HyMotion Backup) and Save to USB. Do not run restore on a healthy new gym. Team still keeps Restore-HyMotion.ps1 next to GMS.Api.exe.', 'ورّي المالك افتح الاستعادة (HyMotion Backup) واحفظ على USB. متستعيدش على نادي جديد سليم. الفريق يحتفظ بسكربت الاستعادة جنب GMS.Api.exe.'), who: 'support', expected: bi('Owner knows: type RESTORE in HyMotion Backup, not in PowerShell. USB copies land in HyMotionBackups on the stick.', 'المالك يعرف: اكتب RESTORE في HyMotion Backup مش في PowerShell. نسخ USB في مجلد HyMotionBackups على الفلاشة.'), verification: bi('HyMotionBackup.exe exists next to the app. Test-Path restore script True for the team.', 'HyMotionBackup.exe جنب التطبيق. سكربت الاستعادة موجود للفريق.'), risk: 'safe', audience: 'support' },
    { id: 'training', action: bi('Staff walkthrough: members, attendance, sale, invoices — modules that exist on this Desk.', 'شرح للموظفين: أعضاء، حضور، بيع، فواتير — الوحدات الموجودة.'), who: 'hyMotion', expected: bi('Owner can add a member and take a sale in the sandbox/live as agreed.', 'المالك يقدر يضيف عضو ويعمل بيعة.'), verification: bi('Owner demonstrates once.', 'المالك يعملها مرة.'), risk: 'safe', audience: 'both' },
    { id: 'golive', action: bi('Complete the Go-Live Acceptance playbook. Operator marks items; nothing auto-completes.', 'كمّل دليل قبول التشغيل. المشغّل يعلّم؛ مفيش إكمال تلقائي.'), who: 'owner', expected: bi('Owner explicit OK.', 'موافقة صريحة.'), verification: bi('Handover checklist all verified or N/A.', 'قائمة التسليم متحققة أو غير منطبقة.'), risk: 'safe', audience: 'both' },
  ],
  failures: [
    {
      id: 'sql-missing',
      title: bi('SQL Server not found', 'SQL Server مش موجود'),
      whatHappened: bi('Installer CheckSqlServerAvailable failed or service cannot open the database.', 'فحص SQL في المثبّت فشل أو الخدمة مش بتفتح القاعدة.'),
      doNot: bi('Do not point Local at a random remote SQL. Do not grant sysadmin to NETWORK SERVICE.', 'متوجّهش المحلي على SQL عشوائي. متديش sysadmin للخدمة.'),
      immediate: bi('Install SQL Express, re-run Test-SqlServerAvailability.ps1 -WriteConfig elevated.', 'ثبّت Express وأعد سكربت الفحص بصلاحية مسؤول.'),
      recovery: bi('Official download is documented in the installer message.', 'رابط التحميل في رسالة المثبّت.'),
      escalation: bi('Escalate if SQL is installed but Windows auth from the installing user fails.', 'صعّد لو SQL متثبت وويندوز أوث يفشل.'),
      logs: bi('Test-SqlServerAvailability.ps1 console; config appsettings.json', 'كونسول الفحص؛ appsettings.json'),
      customerMessage: bi('HyMotion Local needs SQL Server Express on this PC before it can open.', 'المحلي محتاج SQL Express على الجهاز قبل ما يفتح.'),
      closure: bi('Health 200 after SQL is reachable.', 'صحة 200 بعد ما SQL يوصل.'),
      tech: bi('Do not point Local at a random remote SQL. Do not grant sysadmin to NETWORK SERVICE. Official Express download is in the installer message. Re-run Test-SqlServerAvailability.ps1 -WriteConfig elevated after Express is installed.', 'متوجّهش المحلي على SQL عشوائي بعيد. متديش sysadmin. بعد تثبيت Express أعد السكربت -WriteConfig كمسؤول.'),
    },
  ],
  recovery: { en: 'Fix SQL/service/license, then resume from the failed step. Do not skip backup on Local.', ar: 'صلّح SQL/الخدمة/الترخيص وكمل من الخطوة. متتخطاش النسخ في المحلي.' },
  escalation: { en: 'License device limit, SQL permission, or service crash loops.', ar: 'حد أجهزة الترخيص، صلاحية SQL، أو انهيار الخدمة.' },
  customerCommunication: { en: 'We will confirm when the gym can start using HyMotion. Until then please do not enter live members.', ar: 'هنأكد امتى النادي يبدأ يستخدم. لحد وقتها متدخلوش أعضاء حقيقيين.' },
  securityWarnings: [
    bi('NETWORK SERVICE gets db_owner on HyMotionLocal only — never sysadmin.', 'NETWORK SERVICE = db_owner على القاعدة بس.'),
    bi('Jwt/secrets stay on the machine (ProgramData). Do not copy secrets into tickets.', 'الأسرار على الجهاز. متلصقهاش في التذاكر.'),
  ],
  finalVerification: [
    bi('Health 200 (Local) or tenant reachable (SaaS)', 'صحة 200 أو الصالة السحابية واصلة'),
    bi('Owner login', 'دخول المالك'),
    bi('Local: Healthy backup', 'المحلي: نسخة سليمة'),
  ],
  closure: [
    bi('Edition recorded', 'الإصدار متسجل'),
    bi('Owner signed in', 'المالك دخل'),
    bi('Go-live checklist done', 'قائمة التشغيل خلصت'),
    bi('Support owns the case', 'الدعم مسؤول عن الحالة'),
    bi('Case closed', 'الحالة اتقفلت'),
  ],
}

export const handoverPlaybook: Playbook = {
  id: 'golive-handover',
  category: 'handover',
  title: { en: 'Try the gym', ar: 'جرّب النادي' },
  purpose: {
    en: 'Explicit owner verification before HyMotion is called live. Nothing is accepted automatically.',
    ar: 'تحقق صريح من المالك قبل ما نسمّي النظام شغال. مفيش قبول تلقائي.',
  },
  whenToUse: { en: 'After HyMotion already opens on the PC. Not part of Setup itself.', ar: 'بعد ما HyMotion يبقى بيفتح على الجهاز. مش جزء من الإعداد نفسه.' },
  preconditions: [bi('Setup playbook reached training.', 'دليل التجهيز وصل للتدريب.')],
  requiredAccess: { en: 'Owner on the Desk. Support observes.', ar: 'المالك على المكتب. الدعم يراقب.' },
  risk: 'safe',
  audience: 'both',
  customerSummary: {
    en: 'Sign in, add a member, do one daily action, save a copy. That is enough to go live.',
    ar: 'ادخل، ضيف عضو، اعمل حاجة يومية، احفظ نسخة. كده كفاية للتشغيل.',
  },
  steps: [
    { id: 'login', action: bi('Sign in as the gym owner.', 'ادخل بحساب مالك النادي.'), who: 'owner', expected: bi('You see the gym home screen.', 'شايف الشاشة الرئيسية للنادي.'), verification: bi('Your password stays on this PC. Do not send it in a message.', 'كلمة السر على الجهاز. متبعتهاش في رسالة.'), risk: 'safe', audience: 'both' },
    { id: 'owner-feat', action: bi('Owner opens Staff, Roles, Settings, and Backup (Local only).', 'المالك يفتح موظفون وأدوار وإعدادات والنسخ (محلي).'), who: 'owner', expected: bi('OwnerOnly pages visible.', 'صفحات المالك ظاهرة.'), verification: bi('Staff user cannot open Backup.', 'موظف عادي يفتحش النسخ.'), risk: 'safe', audience: 'support' },
    { id: 'staff', action: bi('One staff account with limited permissions.', 'حساب موظف بصلاحيات محدودة.'), who: 'owner', expected: bi('Matches Roles page.', 'يطابق الأدوار.'), verification: bi('Denied page is clear, not a blank crash.', 'المنع واضح مش شاشة فاضية.'), risk: 'safe', audience: 'support' },
    { id: 'members', action: bi('Add one member, or open a member you already have.', 'ضيف عضو، أو افتح عضو موجود.'), who: 'staffOnPc', expected: bi('The member name is on the screen.', 'اسم العضو على الشاشة.'), verification: bi('You can find that member again in the list.', 'تقدر تلاقي العضو تاني في القائمة.'), risk: 'safe', audience: 'both' },
    { id: 'memberships', action: bi('Plans and a membership on a member.', 'الباقات وعضوية على عضو.'), who: 'staffOnPc', expected: bi('Status visible.', 'الحالة ظاهرة.'), verification: bi('Owner OK.', 'موافقة المالك.'), risk: 'safe', audience: 'support' },
    { id: 'attendance', action: bi('Take one check-in or one sale — whatever you use at the door today.', 'اعمل حضور مرة أو بيعة مرة — اللي بتستخدموه عند الباب النهارده.'), who: 'staffOnPc', expected: bi('It saved. If you do not use that screen, tap This is done anyway.', 'اتحفظ. لو مش بتستخدم الشاشة دي، اضغط الخطوة دي خلصت.'), verification: bi('You saw the result, or you do not use it yet.', 'شفت النتيجة، أو لسه مش بتستخدموها.'), risk: 'safe', audience: 'both' },
    { id: 'sales', action: bi('Sale (POS retail) if sales feature flag is on.', 'بيع لو وحدة المبيعات شغالة.'), who: 'staffOnPc', expected: bi('Cart can complete or N/A.', 'السلة تكتمل أو غير منطبق.'), verification: bi('Owner OK.', 'موافقة المالك.'), risk: 'safe', audience: 'support' },
    { id: 'invoices', action: bi('Invoices list / one invoice.', 'الفواتير / فاتورة.'), who: 'staffOnPc', expected: bi('Opens.', 'بتفتح.'), verification: bi('Owner OK.', 'موافقة المالك.'), risk: 'safe', audience: 'support' },
    { id: 'payments', action: bi('A payment path used in Sale/invoices — no separate payments product.', 'مسار دفع من البيع/الفواتير — مفيش منتج مدفوعات منفصل.'), who: 'staffOnPc', expected: bi('Recorded or N/A.', 'اتسجل أو غير منطبق.'), verification: bi('Owner OK.', 'موافقة المالك.'), risk: 'safe', audience: 'support' },
    { id: 'reports', action: bi('Reports page if they have access.', 'التقارير لو عنده صلاحية.'), who: 'owner', expected: bi('Loads or empty state, not an error loop.', 'تحمل أو فاضية، مش خطأ.'), verification: bi('Owner OK.', 'موافقة المالك.'), risk: 'safe', audience: 'support' },
    { id: 'printer', action: bi('Receipt print from Sale/Invoices if they use paper. PVC: one gym-branded blank (Access cards playbook). No HyMotion printer wizard.', 'طباعة إيصال من البيع/الفواتير لو بيستخدموا ورق. PVC: كرت فاضي بعلامة النادي (دليل الكروت). مفيش معالج طابعة HyMotion.'), who: 'staffOnPc', expected: bi('N/A or one print / one card.', 'غير منطبق أو طبعة / كرت.'), verification: bi('Marked by operator.', 'المشغّل علّم.'), risk: 'safe', audience: 'support' },
    { id: 'barcode', action: bi('If PVC sold: scan AccessCard.Code at attendance. Otherwise member number/barcode readable.', 'لو PVC اتباع: امسح AccessCard.Code في الحضور. غير كده رقم/باركود العضو مقروء.'), who: 'staffOnPc', expected: bi('Spot-check.', 'عينة.'), verification: bi('Owner OK.', 'موافقة المالك.'), risk: 'safe', audience: 'support' },
    { id: 'uploads', action: bi('Save one member photo from the member screen.', 'احفظ صورة عضو من شاشة العضو.'), who: 'staffOnPc', expected: bi('The photo shows on the member.', 'الصورة تظهر على العضو.'), verification: bi('Owner OK.', 'موافقة المالك.'), risk: 'safe', audience: 'support' },
    { id: 'backup', action: bi('Owner: open Backup, click Save a copy now, wait until it says the copy is OK.', 'المالك: افتح النسخ، اضغط احفظ نسخة دلوقتي، استنى لحد ما يقول النسخة تمام.'), who: 'owner', expected: bi('A new row says the copy is good.', 'صف جديد يقول النسخة كويسة.'), verification: bi('You did not get an error. If you did, tap I need help.', 'مفيش خطأ. لو فيه، اضغط محتاج مساعدة.'), risk: 'safe', audience: 'both' },
    { id: 'restore-ready', action: bi('Owner tried (or watched) Save to USB and heard: Open Restore opens HyMotion Backup; type RESTORE there. PowerShell is for the HyMotion team.', 'المالك جرّب (أو شاف) احفظ على USB وسمع: افتح الاستعادة بيفتح HyMotion Backup؛ اكتب RESTORE هناك. PowerShell لفريق HyMotion.'), who: 'support', expected: bi('No expectation of an in-browser Restore Run (the API cannot stop its own Windows service).', 'مفيش توقع زر تشغيل استعادة داخل المتصفح (الـ API يقدرش يوقف خدمته).'), verification: bi('Owner repeats: USB folder HyMotionBackups; type RESTORE in the Backup app.', 'المالك يعيد: مجلد HyMotionBackups؛ اكتب RESTORE في تطبيق النسخ.'), risk: 'safe', audience: 'support' },
    { id: 'i18n', action: bi('Switch the language to Arabic or English if you need it.', 'بدّل اللغة عربي أو إنجليزي لو محتاج.'), who: 'owner', expected: bi('The screens match the language you picked.', 'الشاشات بنفس اللغة اللي اخترتها.'), verification: bi('You can read the home screen.', 'تقدر تقرا الشاشة الرئيسية.'), risk: 'safe', audience: 'both' },
    { id: 'theme', action: bi('Desk dark/light if the top bar toggle exists on that build. Control Plane playbook has its own preview theme.', 'فاتح/غامق في المكتب لو الزر موجود. دليل العمليات له ثيم معاينة.'), who: 'owner', expected: bi('Toggle works or N/A.', 'الزر يشتغل أو غير منطبق.'), verification: bi('Owner OK.', 'موافقة المالك.'), risk: 'safe', audience: 'support' },
  ],
  failures: [],
  recovery: { en: 'Fix the failing module, then uncheck and re-verify. Do not close go-live with failed money/login checks.', ar: 'صلّح الوحدة وأعد التحقق. متقفلش التشغيل ولو الدخول/الفلوس فاشلين.' },
  escalation: { en: 'Login failure, missing OwnerOnly pages, or Backup page bounce on Local.', ar: 'فشل دخول، اختفاء صفحات المالك، أو صفحة النسخ بترجع في المحلي.' },
  customerCommunication: { en: 'Go-live means you tried these items with us. We will not tick them for you.', ar: 'التشغيل يعني جربتوا البنود معانا. مش هنعلّمها عنكم.' },
  securityWarnings: [bi('Do not share owner password in the ticket.', 'متشاركش كلمة سر المالك في التذكرة.')],
  finalVerification: [bi('Every step completed, blocked with reason, or N/A.', 'كل خطوة مكتملة أو متوقفة بسبب أو غير منطبقة.')],
  closure: [
    bi('Owner explicit go-live OK', 'موافقة تشغيل صريحة'),
    bi('Failed items escalated or accepted', 'البنود الفاشلة اتصعّدت أو اتقبلت'),
    bi('Case closed', 'الحالة اتقفلت'),
  ],
}
