import type { Playbook } from '../types'
import { bi } from '../i18n'

export const supportPlaybooks: Playbook[] = [
  {
    id: 'svc-wont-open',
    category: 'support',
    title: { en: 'Application will not open', ar: 'التطبيق مش بيفتح' },
    purpose: { en: 'Local Desk not loading in the browser.', ar: 'مكتب المحلي مش بيفتح في المتصفح.' },
    whenToUse: { en: 'The HyMotion window does not open on the gym PC.', ar: 'نافذة HyMotion مش بتفتح على جهاز النادي.' },
    preconditions: [bi('This is Local Edition on that PC.', 'دي النسخة المحلية على الجهاز.')],
    requiredAccess: { en: 'Someone on the gym PC. Support may ask for service status.', ar: 'حد على جهاز النادي.' },
    risk: 'admin',
    audience: 'both',
    customerSummary: { en: 'Please do not keep clicking. We will check whether HyMotion is running on this PC.', ar: 'متفضلوش تضغطوا. هنشوف HyMotion شغال على الجهاز ولا لأ.' },
    steps: [
      { id: 'url', action: bi('Double-click the HyMotion icon on the desktop.', 'دبل كليك أيقونة HyMotion على سطح المكتب.'), who: 'customer', expected: bi('You see the sign-in page or the home screen.', 'تشوف صفحة الدخول أو الشاشة الرئيسية.'), verification: bi('You can type the gym username. If the page never loads, tap I need help.', 'تقدر تكتب اسم المستخدم. لو الصفحة عمرها ما فتحت، اضغط محتاج مساعدة.'), risk: 'safe', audience: 'both', tech: bi('Launcher is HyMotionLauncher.exe next to GMS.Api.exe. Local binds loopback :7140. GET /health via MapHealthChecks. Do not use :5000 or a LAN IP unless a security review approved it.', 'Launcher جنب GMS.Api.exe. المحلي على 7140. متستخدمش 5000 أو IP شبكة من غير مراجعة.') },
      { id: 'svc', action: bi('On the PC, check whether the HyMotion Windows service is running. If it is stopped, start it as Administrator.', 'على الجهاز، شوف خدمة ويندوز HyMotion شغالة ولا لأ. لو واقفة، شغّلها كمسؤول.'), who: 'support', expected: bi('Service is Running.', 'الخدمة Running.'), verification: bi('Health 200.', 'صحة 200.'), risk: 'admin', audience: 'support', tech: bi('Get-Service HyMotion; Start-Service HyMotion. Account NETWORK SERVICE. If missing entirely: install-service.ps1 from the published folder.', 'Get-Service / Start-Service HyMotion. لو مش موجودة: install-service.ps1.'), commands: [
        { id: 'svc', label: bi('Service status', 'حالة الخدمة'), text: 'Get-Service HyMotion | Format-List Status, StartType, Name', supportOnly: true },
      ] },
    ],
    failures: [
      {
        id: 'sql-down',
        title: bi('Database unavailable', 'قاعدة البيانات مش متاحة'),
        whatHappened: bi('Service starts then dies, or login loops, because SQL is down or the login has no rights.', 'الخدمة تقوم وتقع لأن SQL واقف أو مفيش صلاحية.'),
        doNot: bi('Do not restore to “fix” a stopped SQL service.', 'متستعيدش عشان تصلّح SQL واقف.'),
        immediate: bi('Start SQL Server (MSSQLSERVER or MSSQL$SQLEXPRESS). Confirm ProgramData connection string.', 'شغّل خدمة SQL. أكد سلسلة الاتصال.'),
        recovery: bi('Test-SqlServerAvailability.ps1 diagnostic (no -WriteConfig unless installing).', 'سكربت الفحص من غير كتابة إعداد إلا وقت التثبيت.'),
        escalation: bi('SQL running but NETWORK SERVICE cannot open HyMotionLocal.', 'SQL شغال و NETWORK SERVICE يفتحش القاعدة.'),
        logs: bi('Windows Application log; GMS.Api if present', 'سجلات ويندوز'),
        customerMessage: bi('The gym app needs a program on this PC that is not running. Tap I need help. Do not restore.', 'التطبيق محتاج برنامج على الجهاز مش شغال. اضغط محتاج مساعدة. متستعيدش.'),
        closure: bi('Owner opened HyMotion.', 'المالك فتح HyMotion.'),
        audience: 'support',
        tech: bi('Start MSSQLSERVER or MSSQL$SQLEXPRESS. Connection string in C:\\ProgramData\\HyMotion\\config\\appsettings.json. Diagnostic: Test-SqlServerAvailability.ps1 without -WriteConfig unless installing. NETWORK SERVICE must be db_owner on HyMotionLocal.', 'شغّل خدمة SQL. سلسلة الاتصال في appsettings.json. الفحص من غير -WriteConfig إلا وقت التثبيت.'),
      },
    ],
    recovery: { en: 'Start service, start SQL, then health.', ar: 'شغّل الخدمة و SQL ثم الصحة.' },
    escalation: { en: 'Service missing entirely — install-service.ps1.', ar: 'الخدمة مش موجودة — install-service.ps1.' },
    customerCommunication: { en: 'Stay on this PC. Double-click HyMotion on the desktop.', ar: 'خلّوا الجهاز ده. دبل كليك HyMotion على سطح المكتب.' },
    securityWarnings: [bi('Do not expose 0.0.0.0 without a security review (Local is loopback).', 'متفتحش 0.0.0.0 من غير مراجعة.')],
    finalVerification: [bi('Health 200 and login page.', 'صحة 200 وصفحة دخول.')],
    closure: [bi('Owner opened the Desk', 'المالك فتح المكتب'), bi('Case closed', 'الحالة اتقفلت')],
  },
  {
    id: 'access-login',
    category: 'access',
    title: { en: 'Login or permission problem', ar: 'مشكلة دخول أو صلاحية' },
    purpose: { en: 'Owner/staff cannot sign in or cannot see a page.', ar: 'المالك/موظف مش عارف يدخل أو يشوف صفحة.' },
    whenToUse: { en: 'Cannot sign in, or a page is missing.', ar: 'مش قادر تدخل، أو صفحة مش ظاهرة.' },
    preconditions: [bi('App opens.', 'التطبيق بيفتح.')],
    requiredAccess: { en: 'Owner for Staff/Roles. Support does not reset passwords over chat.', ar: 'المالك للموظفين/الأدوار. الدعم مش بيصفر كلمات السر في الشات.' },
    risk: 'safe',
    audience: 'both',
    customerSummary: { en: 'We will check which account you use. We will not ask you to type your password into a message.', ar: 'هنشوف أنهي حساب. مش هنطلب كلمة السر في رسالة.' },
    steps: [
      { id: 'which-user', action: bi('Open HyMotion on the gym PC. Try the owner login first, then a staff login. Do not type the password into a chat message.', 'افتح HyMotion على جهاز النادي. جرّب دخول المالك الأول، بعدين موظف. متكتبش كلمة السر في رسالة.'), who: 'customer', expected: bi('One of the two accounts can sign in, or you know which one is blocked.', 'واحد من الحسابين يدخل، أو عارف أنهي واقف.'), verification: bi('You reach the home screen, or you tap I need help.', 'وصلت للشاشة الرئيسية، أو ضغطت محتاج مساعدة.'), risk: 'safe', audience: 'both' },
      { id: 'roles', action: bi('Owner: open Staff and Roles. Backup is for the owner. Cards need their own permission.', 'المالك: افتح الموظفون والأدوار. النسخ للمالك. الكروت ليها صلاحية لوحدها.'), who: 'owner', expected: bi('Staff see only what you allowed.', 'الموظف شايف اللي سمحت بيه بس.'), verification: bi('A cashier cannot open Backup.', 'الكاشير يفتحش النسخ.'), risk: 'safe', audience: 'both' },
      { id: 'owner-reset', action: bi('If the owner forgot the Local Desk password: Ops records owner-password-reset on the customer (reason ≥ 10 characters). That does not change a password — complete it on the gym PC. If this is a Cloud tenant Owner, Ops sets a new password from Gyms → Cloud → Users. Never log or chat the password. Gym-side staff-reset still refuses Owner.', 'لو المالك نسي كلمة سر المكتب المحلي: العمليات تسجّل طلب تصفير على العميل (سبب ≥ 10 حروف). ده مش بيغيّر كلمة السر — التصفير على جهاز النادي. لو مالك سحابي، العمليات تعيّن كلمة جديدة من الصالات ← سحابي ← المستخدمون. متسجلش ولا تشارك الكلمة. تصفير الموظفين على الجهاز بيرفض Owner.'), who: 'hyMotion', expected: bi('Local: OwnerAccountStatus = reset requested. Cloud: owner can sign in with the new password. No password in API JSON or tickets.', 'المحلي: حالة الحساب = مطلوب تصفير. السحابة: المالك يدخل بالكلمة الجديدة. مفيش كلمة سر في JSON أو التذاكر.'), verification: bi('Ticket has no password. Local owner signs in after the on-PC reset. Cloud owner signs in after Ops reset.', 'التذكرة من غير كلمة سر. مالك المحلي يدخل بعد التصفير على الجهاز. مالك السحابة يدخل بعد تصفير العمليات.'), risk: 'admin', audience: 'support', tech: bi('Local request-only: POST /platform-api/customers/{id}/owner-password-reset OpsOrAbove. Cloud: POST /platform-api/tenants/{tenantId}/users/{staffId}/reset-password OpsOrAbove allowOwner, never returns the password. Gym-side AdminService.ResetStaffPasswordAsync still refuses Owner.', 'طلب المحلي Ops+. السحابة reset-password Ops+ ويسمح بالمالك. تصفير الموظفين على الجهاز بيرفض Owner.') },
    ],
    failures: [],
    recovery: { en: 'Owner grants permission or uses owner login.', ar: 'المالك يدي صلاحية أو يدخل بحسابه.' },
    escalation: { en: 'Owner locked out after restore (wrong backup day) — Restore playbook case 13.', ar: 'المالك اتقفل بعد استعادة — حالة 13.' },
    customerCommunication: { en: 'Please sign in as owner to change staff permissions.', ar: 'ادخلوا كمالك لتغيير صلاحيات الموظفين.' },
    securityWarnings: [bi('Never request passwords or OTP codes in tickets.', 'متطلبش كلمات سر أو OTP في التذاكر.')],
    finalVerification: [bi('User reaches the intended page.', 'المستخدم وصل للصفحة.')],
    closure: [bi('Access confirmed', 'الوصول اتأكد'), bi('Case closed', 'الحالة اتقفلت')],
  },
  {
    id: 'pc-replace',
    category: 'support',
    title: { en: 'PC replacement', ar: 'تبديل جهاز' },
    purpose: { en: 'New hardware for Local Edition.', ar: 'عتاد جديد للنسخة المحلية.' },
    whenToUse: { en: 'Disk death, theft, upgrade.', ar: 'عطل قرص، سرقة، ترقية.' },
    preconditions: [bi('Off-PC backup folder or old disk still readable.', 'نسخة برا الجهاز أو القرص القديم مقروء.')],
    requiredAccess: { en: 'Ops for license device transfer. Admin on new PC.', ar: 'عمليات لنقل الترخيص. مسؤول على الجهاز الجديد.' },
    risk: 'destructive',
    audience: 'support',
    customerSummary: { en: 'The new PC starts empty. We restore only if you kept a backup folder off the old PC.', ar: 'الجهاز الجديد فاضي. هنستعيد لو عندكم مجلد نسخ برا القديم.' },
    steps: [
      { id: 'copy', action: bi('Copy HyMotionBackup_* folders to the new PC ProgramData Backups, or import from <USB>:\\HyMotionBackups\\ via HyMotion Backup.', 'انسخ مجلدات النسخ لـ Backups على الجديد، أو استورد من HyMotionBackups على الـ USB عبر HyMotion Backup.'), who: 'support', expected: bi('manifest + bak + zip present.', 'الملفات الثلاثة موجودة.'), verification: bi('Restore playbook case 17.', 'حالة 17.'), risk: 'admin', audience: 'support' },
      { id: 'customer', action: bi('Open the Control Plane customer (not a loose license). Confirm contract still active. Ops authorizes license transfer on the old installation, then activate on the new PC after restore.', 'افتح عميل لوحة التحكم (مش ترخيص سايب). أكد العقد لسه نشط. العمليات تصرّح بنقل الترخيص على التثبيت القديم، بعدين التفعيل على الجهاز الجديد بعد الاستعادة.'), who: 'hyMotion', expected: bi('Same customer, same license key if Ops transferred — do not issue a second lifetime unless the old one is revoked.', 'نفس العميل ونفس المفتاح لو النقل اتعمل — متصدرش مدى حياة تاني إلا لو القديم اتسحب.'), verification: bi('Customer profile shows the license and new installation after activation.', 'ملف العميل فيه الترخيص والتثبيت الجديد بعد التفعيل.'), risk: 'admin', audience: 'support' },
      { id: 'license', action: bi('Do not invent a license API. Use Licenses detail → Authorize transfer (Ops/Admin, reason required). Sales cannot transfer.', 'متخترعش API ترخيص. استخدم تفاصيل الترخيص ← تصريح النقل (عمليات، سبب مطلوب). المبيعات تنقلش.'), who: 'hyMotion', expected: bi('License status active on the new device as the page allows.', 'حالة الترخيص نشطة كما تسمح الصفحة.'), verification: bi('See license-lifecycle playbook.', 'شوف دليل دورة الترخيص.'), risk: 'admin', audience: 'support' },
    ],
    failures: [],
    recovery: { en: 'Without backup folders, only a fresh empty gym is possible.', ar: 'من غير مجلدات النسخ يبقى نادي فاضي جديد.' },
    escalation: { en: 'Device limit exceeded.', ar: 'تجاوز حد الأجهزة.' },
    customerCommunication: { en: 'Please keep USB backups. A dead PC without them cannot bring members back.', ar: 'احتفظوا بنسخ USB. جهاز ميت من غيرهم مش هيرجّع الأعضاء.' },
    securityWarnings: [bi('Treat backup folders as the gym database.', 'مجلدات النسخ = قاعدة النادي.')],
    finalVerification: [bi('Health 200, owner login, restore verification.', 'صحة 200 ودخول وتحقق استعادة.')],
    closure: [bi('New PC live', 'الجهاز الجديد شغال'), bi('Case closed', 'الحالة اتقفلت')],
  },
]

export const updatePlaybook: Playbook = {
  id: 'update-local',
  category: 'updates',
  title: { en: 'Software update / upgrade', ar: 'تحديث البرنامج' },
  purpose: { en: 'Say what we actually know about updates. There is no verified one-click updater.', ar: 'نقول اللي معروف عن التحديث. مفيش محدّث بضغطة متحقَّق.' },
  whenToUse: { en: 'Owner asks to update Local or SaaS.', ar: 'المالك يطلب تحديث.' },
  preconditions: [bi('Identify edition.', 'حدد الإصدار.')],
  requiredAccess: { en: 'Administrator on PC for Local. Platform ops for SaaS deploys (not in this console as a button).', ar: 'مسؤول الجهاز للمحلي.' },
  risk: 'destructive',
  audience: 'support',
  customerSummary: { en: 'UPDATE PROCEDURE NOT VERIFIED as a single customer-safe wizard. We will not click imaginary Update.', ar: 'إجراء التحديث مش متحقَّق كمعالج واحد. مش هنضغط تحديث وهمي.' },
  steps: [
    { id: 'backup-first', action: bi('Local: take Backup now and confirm Healthy before any file replace.', 'المحلي: نسخ دلوقتي وسليم قبل أي تبديل ملفات.'), who: 'support', expected: bi('Healthy row.', 'صف سليم.'), verification: bi('Backup playbook.', 'دليل النسخ.'), risk: 'admin', audience: 'support' },
    { id: 'unverified', action: bi('Inno Setup script supports upgrades via AppVersion, but it is marked not built/verified in-repo. SaaS app update is a server deploy, not a Desk button.', 'سكربت Inno يدعم الترقية عبر AppVersion لكنه غير مبني/متحقَّق في المستودع. تحديث السحابة نشر سيرفر مش زر.'), who: 'support', expected: bi('UPDATE PROCEDURE NOT VERIFIED.', 'إجراء التحديث مش متحقَّق.'), verification: bi('Do not tell the owner there is an in-app updater.', 'متقولش للمالك إن في محدّث داخل التطبيق.'), risk: 'support_only', audience: 'support', unsupported: true },
  ],
  failures: [],
  recovery: { en: 'Restore from the Healthy backup taken before the attempt.', ar: 'استعادة من النسخة السليمة قبل المحاولة.' },
  escalation: { en: 'Any production upgrade attempt must be planned with engineering; this playbook does not authorize one.', ar: 'أي ترقية إنتاج تتخطيط هندسي؛ الدليل مش بيصرّح بيها.' },
  customerCommunication: { en: 'There is no verified one-click update in the gym Desk. Support will schedule a backup first if files must change.', ar: 'مفيش تحديث بضغطة متحقَّق في المكتب. الدعم هينسّق نسخة الأول لو الملفات لازم تتغير.' },
  securityWarnings: [bi('Never overwrite ProgramData backups with an old installer folder.', 'متكتبش فوق مجلد النسخ بمثبّت قديم.')],
  finalVerification: [bi('If no files changed: close as not executed. If files changed despite the gap: health + login + backup.', 'لو الملفات ما اتغيرتش: اقفل كغير منفّذ. لو اتغيرت: صحة ودخول ونسخ.')],
  closure: [bi('Owner informed there is no verified updater', 'المالك اتعرف إن مفيش محدّث متحقَّق'), bi('Case closed', 'الحالة اتقفلت')],
}

export const policiesPlaybook: Playbook = {
  id: 'ops-policies',
  category: 'policies',
  title: { en: 'Customer communication / operational policies', ar: 'تواصل العميل / سياسات التشغيل' },
  purpose: {
    en: 'Internal HyMotion policy vs customer-facing recommendation. Not legal terms.',
    ar: 'سياسة HyMotion الداخلية مقابل توصية للعميل. مش بنود قانونية.',
  },
  whenToUse: { en: 'Before restore, remote sessions, data-loss talks.', ar: 'قبل الاستعادة، الجلسات عن بعد، حديث فقدان البيانات.' },
  preconditions: [],
  requiredAccess: { en: 'All HyMotion roles. Destructive actions still need Admin on the PC.', ar: 'كل أدوار HyMotion. التدميري لسه محتاج مسؤول على الجهاز.' },
  risk: 'safe',
  audience: 'support',
  customerSummary: {
    en: 'We will say clearly what we can do from here and what needs you at the PC.',
    ar: 'هنقول بوضوح إيه اللي نقدر نعمله من هنا وإيه اللي محتاجكم على الجهاز.',
  },
  steps: [
    { id: 'remote', action: bi('Internal: Support can view Control Plane (tenants, licenses, audit). Support cannot remotely run Restore-HyMotion.ps1 from this playbook UI.', 'داخلي: الدعم يشوف لوحة التحكم. مش بيقدّر يشغّل الاستعادة عن بعد من الشاشة دي.'), who: 'support', expected: bi('No fake Run button.', 'مفيش زر تشغيل وهمي.'), verification: bi('This page offers Copy command only.', 'الصفحة فيها نسخ أمر بس.'), risk: 'safe', audience: 'support' },
    { id: 'approval', action: bi('Internal: Restore, SkipSafetyBackup, license revoke/suspend need owner or Ops approval as the existing UIs already enforce for licenses.', 'داخلي: الاستعادة وتخطي الاحترازية وسحب الترخيص محتاجين موافقة كما تفرض الشاشات.'), who: 'support', expected: bi('Customer-facing: we will not restore without telling you downtime.', 'للعميل: مش هنستعيد من غير ما نقول إن في توقف.'), verification: bi('Approval noted on the case.', 'الموافقة على الحالة.'), risk: 'destructive', audience: 'both' },
    { id: 'admin', action: bi('Internal: Service start/stop, restore, nightly task, SQL grants require Administrator on the gym PC.', 'داخلي: الخدمة والاستعادة والمهمة الليلية محتاجين مسؤول على جهاز النادي.'), who: 'support', expected: bi('Customer-facing: someone with PC admin must be present.', 'للعميل: لازم يبقى في حد مسؤول على الجهاز.'), verification: bi('Elevation used when scripts demand it.', 'رفع الصلاحية لما السكربت يطلب.'), risk: 'admin', audience: 'both' },
    { id: 'backup-resp', action: bi('Internal: HyMotion provides Save a copy now + Save to USB (HyMotion Backup → <USB>:\\HyMotionBackups\\). Off-PC copy is still the gym’s job.', 'داخلي: HyMotion بيوفّر احفظ نسخة دلوقتي + احفظ على USB (إلى HyMotionBackups). النسخة برا لسه شغل النادي.'), who: 'owner', expected: bi('Customer-facing: plug in a USB and click Save to USB. A copy only on this PC dies with the PC.', 'للعميل: وصلوا USB واضغطوا احفظ على USB. النسخة على الجهاز تموت مع الجهاز.'), verification: bi('Owner heard it at handover.', 'المالك سمعها عند التسليم.'), risk: 'safe', audience: 'both' },
    { id: 'restore-resp', action: bi('Internal: Owner restore = Open Restore → HyMotion Backup → type RESTORE. Team PowerShell is support-only. Never an in-browser Run.', 'داخلي: استعادة المالك = افتح الاستعادة ← HyMotion Backup ← اكتب RESTORE. PowerShell للفريق. عمره تشغيل جوه المتصفح.'), who: 'support', expected: bi('Owner does not receive -Force snippets.', 'المالك ما ياخدش أوامر -Force.'), verification: bi('Audience toggle Customer hides commands.', 'رؤية العميل بتخفي الأوامر.'), risk: 'destructive', audience: 'both' },
    { id: 'commerce', action: bi('Internal: Customer → Contract → Payment in Control Plane. Sales must not issue/revoke/transfer licenses. Never store gym owner passwords on the customer.', 'داخلي: عميل ← عقد ← دفعة في اللوحة. المبيعات متصدرش/تسحب/تنقل تراخيص. متتخزنش كلمات سر المالك على العميل.'), who: 'hyMotion', expected: bi('Customer-facing: you are a HyMotion customer; the gym Desk login is separate and stays on the PC.', 'للعميل: أنتوا عميل HyMotion؛ دخول المكتب منفصل وعلى الجهاز.'), verification: bi('Customer profile has no password field.', 'ملف العميل من غير حقل كلمة سر.'), risk: 'safe', audience: 'support' },
    { id: 'secrets', action: bi('Internal: never request passwords, OTPs, JWT secrets, or license private files in chat.', 'داخلي: متطلبش كلمات سر أو OTP أو أسرار JWT في الشات.'), who: 'support', expected: bi('Customer-facing: we will never ask you to paste your password.', 'للعميل: مش هنطلب لصق كلمة السر.'), verification: bi('Ticket has no secrets.', 'التذكرة من غير أسرار.'), risk: 'safe', audience: 'both' },
    { id: 'dataloss', action: bi('Internal: if no Healthy/Partial restorable copy exists, say data-loss risk plainly. Not a legal admission of liability.', 'داخلي: لو مفيش نسخة قابلة للاستعادة، قولوا خطر الفقدان بوضوح. مش إقرار مسؤولية قانونية.'), who: 'support', expected: bi('Customer-facing: we cannot recreate members from nothing.', 'للعميل: مش هنركّب الأعضاء من العدم.'), verification: bi('Message sent; case stays open until they acknowledge.', 'الرسالة اتبعتت؛ الحالة مفتوحة لحد الإقرار.'), risk: 'safe', audience: 'both' },
    { id: 'resolved', action: bi('Internal: resolved = verification done, customer informed, no open error, closure checklist ticked by a human.', 'داخلي: الحل = تحقق + إعلام العميل + مفيش خطأ مفتوح + قائمة إغلاق بإيد حد.'), who: 'support', expected: bi('Customer-facing: you can use the gym again, or we said you cannot yet.', 'للعميل: تقدروا تستخدموا أو قلنا لسه.'), verification: bi('Closure boxes in this UI.', 'صناديق الإغلاق هنا.'), risk: 'safe', audience: 'both' },
  ],
  failures: [],
  recovery: { en: 'If policy was violated (e.g. restore without approval), stop, inform owner, escalate.', ar: 'لو السياسة اتكسرت، قف، أعلم المالك، صعّد.' },
  escalation: { en: 'Data-loss, skipped safety backup on production, secrets in a ticket.', ar: 'فقدان بيانات، تخطي احترازية على إنتاج، أسرار في تذكرة.' },
  customerCommunication: { en: 'These are operating rules for HyMotion staff, not a contract.', ar: 'دي قواعد شغل لفريق HyMotion، مش عقد.' },
  securityWarnings: [bi('Operational policies ≠ legal terms of service.', 'سياسات تشغيل ≠ شروط قانونية.')],
  finalVerification: [bi('Audience toggle reviewed for the case type.', 'رؤية العميل/الدعم اتراجعت لنوع الحالة.')],
  closure: [bi('Policy applied', 'السياسة اتطبقت'), bi('Case closed', 'الحالة اتقفلت')],
}
